/* =====================================================================
   DIRECTED ENERGY TRACKER — DATA FILE
   ---------------------------------------------------------------------
   This is the ONLY file that changes during a daily/periodic update.
   The layout (index.html) stays fixed. To update:
     • bump META.lastUpdated (YYYY-MM-DD) and META.dataVersion
     • append items to a program's `news:[]` array (newest first)
     • adjust a `status`, `power`, `cost`, `timeline`, or `suppliers` field
     • set `start:YYYY` (origin year) on every program — it drives the
       chronological era bands; any NEW program MUST include it
     • set `match:[...]` keywords on every program — the page auto-routes
       live news headlines into that program's card using them
     • add a row to DISCREPANCIES if new reporting contradicts old data
   Do NOT edit index.html for content changes.
   ===================================================================== */
window.DE_DATA = {

  META: {
    title: "U.S. Directed Energy Weapon Programs — Live Tracker",
    fyFocus: "FY2027",
    lastUpdated: "2026-06-05",   // <-- bump on every data edit
    dataVersion: 6,
    // Live-news feed (GDELT DOC 2.0 — no API key). Raw query; encoded at runtime.
    newsQuery: '("directed energy" OR "directed-energy weapon" OR "high energy laser" OR "high-energy laser" OR "high power microwave" OR "high-power microwave" OR "laser weapon" OR "laser weapons" OR "counter-drone laser" OR "anti-drone laser" OR "drone-killing laser" OR "Golden Dome" OR "space-based laser" OR "space-based interceptor")',
    newsTimespan: "3m"           // GDELT timespan window (e.g. 1m, 3m, 6m)
  },

  STATUS: {
    active:    {l:"Active",            c:"var(--active)"},
    new:       {l:"New / Successor",   c:"var(--new)"},
    shelved:   {l:"Shelved",           c:"var(--shelved)"},
    concept:   {l:"Lineage / Concept", c:"var(--concept)"},
    fielded:   {l:"Fielded",           c:"var(--fielded)"},
    counter:   {l:"Counter-ASCM",      c:"var(--counter)"},
    demo:      {l:"Demo",              c:"var(--demo)"},
    platform:  {l:"Platform",          c:"var(--platform)"},
    retired:   {l:"Retired",           c:"var(--concept)"},
    concluded: {l:"Concluded",         c:"var(--shelved)"},
    cancelled: {l:"Cancelled",         c:"var(--shelved)"},
    indev:     {l:"In development",     c:"var(--new)"}
  },

  SOURCES: [
    {s:"CRS R46925 (Jul 11 2024)", t:"DoD Directed Energy Weapons: Background & Issues for Congress", u:"https://www.congress.gov/crs-product/R46925"},
    {s:"CRS R44175", t:"Navy Shipboard Lasers: Background & Issues for Congress", u:"https://www.congress.gov/crs-product/R44175"},
    {s:"CRS IF11882 (Jan 2026)", t:"Defense Primer: Directed-Energy Weapons", u:"https://www.congress.gov/crs-product/IF11882"},
    {s:"CRS IF12421 (Jan 2026)", t:"The Army's Indirect Fire Protection Capability (IFPC) System", u:"https://www.congress.gov/crs-product/IF12421"},
    {s:"DoD/War Comptroller", t:"FY2027 Budget Request Overview Book", u:"https://comptroller.war.gov/Portals/45/Documents/defbudget/FY2027/FY2027_Budget_Request_Overview_Book.pdf"},
    {s:"Laser Wars (Apr 8 2026)", t:"The Pentagon's FY2027 Budget Bet on Directed Energy", u:"https://www.laserwars.net/p/defense-department-fy2027-budget-request-directed-energy-laser-weapon-funding"},
    {s:"The Defense News", t:"Pentagon Requests Over $2B for Directed Energy in FY2027", u:"https://www.thedefensenews.com/news-details/Pentagon-Requests-Over-2-Billion-for-Directed-Energy-Research-in-FY2027-Budget/"},
    {s:"Defense News (Apr 28 2026)", t:"What we know about the military's new joint laser weapon system", u:"https://www.defensenews.com/newsletters/daily-news-roundup/2026/04/28/what-we-know-about-the-us-militarys-new-joint-laser-weapon-system/"},
    {s:"Military Times (Mar 23 2026)", t:"The US Army is already ditching its most powerful laser weapon yet", u:"https://www.militarytimes.com/industry/techwatch/2026/03/23/the-us-army-is-already-ditching-its-most-powerful-laser-weapon-yet/"},
    {s:"Military Times (Apr 13 2026)", t:"US military eyes high-energy 'laser dome' for domestic air defense", u:"https://www.militarytimes.com/industry/techwatch/2026/04/13/us-military-eyes-high-energy-laser-dome-for-domestic-air-defense/"},
    {s:"DefenseScoop (Nov 3 2025)", t:"Army takes another step toward E-HEL drone-killing lasers", u:"https://defensescoop.com/2025/11/03/army-enduring-high-energy-laser-ehel-rfi-counter-uas/"},
    {s:"Breaking Defense (Nov 2025)", t:"Give 'em E-HEL: Army seeks industry ideas for C-UAS lasers", u:"https://breakingdefense.com/2025/11/give-em-e-hel-army-seeks-industry-ideas-for-counter-drone-laser-systems/"},
    {s:"DefenseScoop (Feb 18 2026)", t:"Navy brass sees future battleship as catalyst to scale lasers", u:"https://defensescoop.com/2026/02/18/navy-lasers-admiral-caudle-golden-fleet-battleship/"},
    {s:"DefenseScoop (Mar 16 2026)", t:"Inside a 'first of its kind' counter-drone laser test", u:"https://defensescoop.com/2026/03/16/inside-counter-drone-laser-test-new-mexico-white-sands/"},
    {s:"Epirus (Jul 17 2025)", t:"Epirus receives $43.5M for IFPC-HPM Gen II", u:"https://www.epirusinc.com/press-releases/epirus-receives-43-million-contract-from-u-s-army-for-ifpc-hpm-generation-ii-systems"},
    {s:"AeroVironment / BlueHalo", t:"AeroVironment to acquire BlueHalo", u:"https://bluehalo.com/aerovironment-to-acquire-bluehalo/"},
    {s:"AeroVironment", t:"AV delivers first two AMP-HEL (LOCUST) systems to US Army", u:"https://investor.avinc.com/news-releases/news-release-details/av-delivers-first-two-multi-purpose-high-energy-laser-systems-us"},
    {s:"The War Zone (TWZ)", t:"USS Preble used HELIOS to zap four drones", u:"https://www.twz.com/sea/uss-preble-used-helios-laser-to-zap-four-drones-in-expanding-testing"},
    {s:"optics.org / Naval News", t:"Coherent wins ~$30M for 400 kW Songbow laser; HELCAP 300 kW", u:"https://optics.org/news/16/6/21"},
    {s:"Task & Purpose", t:"Pentagon names five bases for anti-drone energy weapons", u:"https://taskandpurpose.com/news/laser-drones-pentagon-base-defense/"},
    {s:"GovConWire / ExecutiveGov", t:"Army FY2027 C-sUAS budget ($994.1M SHORAD line)", u:"https://www.govconwire.com/articles/csuas-army-fy2027-budget-cuas-raytheon-aerovironment"},
    {s:"CSIS", t:"Unpacking the $1.5T FY2027 Defense Budget Topline", u:"https://www.csis.org/analysis/unpacking-15-trillion-fy-2027-defense-budget-topline"},
    {s:"Breaking Defense (Mar 2025) — HII HEL", t:"Army awards HII tech division contract to develop high-energy laser", u:"https://breakingdefense.com/2025/03/army-awards-hiis-tech-division-contract-to-develop-high-energy-laser/"},
    {s:"AeroVironment (Jun 3 2026)", t:"Milestones at White Sands: Driscoll's test & the FAA/DoW safety agreement", u:"https://www.avinc.com/2026/06/03/milestones-at-white-sands-driscolls-test-the-faa-and-dows-landmark-safety-agreement/"},
    {s:"Military Times (Jun 2 2026)", t:"The US military wants to showcase battle-ready laser weapons by 2028", u:"https://www.militarytimes.com/industry/techwatch/2026/06/02/the-us-military-wants-to-showcase-battle-ready-laser-weapons-by-2028/"},
    {s:"The War Zone — Leonidas", t:"Army puts $50M bet on next-gen Leonidas HPM counter-drone tech", u:"https://www.twz.com/land/army-puts-50m-bet-on-next-gen-leonidas-high-power-microwave-counter-drone-tech"},
    {s:"Laser Wars (May 30 2026)", t:"Last Ride of the HELIOS — Congress pushes a containerized HELIOS", u:"https://www.laserwars.net/p/navy-helios-laser-weapon-containerization"},
    {s:"Laser Wars (Mar 5 2026)", t:"US Navy laser weapon in Operation Epic Fury", u:"https://www.laserwars.net/p/us-navy-laser-weapon-iran-operation-epic-fury"},
    {s:"USNI News (May 11 2026)", t:"Trump-class battleship will be nuclear-powered", u:"https://news.usni.org/2026/05/11/new-navy-shipbuilding-plan-trump-class-battleship-will-be-nuclear-powered-carrier-design-is-under-review"},
    {s:"DefenseScoop (May 19 2026)", t:"Battleship comes full circle: Navy BBG(X)/BBGN nuclear program", u:"https://defensescoop.com/2026/05/19/battleship-nuclear-power-navy-bbgx-bbgn-program/"},
    {s:"Defense News (Mar 31 2026)", t:"The US Navy brought a one-of-a-kind laser weapon back from the dead", u:"https://www.defensenews.com/industry/techwatch/2026/03/31/the-us-navy-brought-a-one-of-a-kind-laser-weapon-back-from-the-dead/"},
    {s:"Naval News (Apr 2026)", t:"AV demonstrates LOCUST laser aboard an aircraft carrier", u:"https://www.navalnews.com/event-news/sea-air-space-2026/2026/04/av-demonstrates-locust-laser-weapon-system-aboard-aircraft-carrier/"},
    {s:"The War Zone — LOCUST carrier", t:"Navy fires drone-frying LOCUST laser from supercarrier USS George H.W. Bush", u:"https://www.twz.com/news-features/navy-fires-dronefrying-locust-laser-from-supercarrier-uss-george-h-w-bush"},
    {s:"Breaking Defense (Mar 24 2026)", t:"AV unveils LOCUST X3, latest entrant in the laser counter-drone race", u:"https://breakingdefense.com/2026/03/av-unveils-locust-x3-latest-entrant-into-laser-counter-drone-race/"},
    {s:"USNI News (Mar 2024)", t:"Navy to test microwave anti-drone weapon at sea in 2026 (Project METEOR)", u:"https://news.usni.org/2024/03/27/navy-to-test-microwave-anti-drone-weapon-at-sea-in-2026"},
    {s:"RTX (Jan 29 2024) — CHIMERA", t:"RTX's CHIMERA high-power microwave system excels during three-week field test", u:"https://www.rtx.com/news/news-center/2024/01/29/rtxs-chimera-high-power-microwave-system-excels-during-three-week-field-test"},
    {s:"Naval News (Apr 2025)", t:"General Atomics confirms drone-killing air-to-air laser in development", u:"https://www.navalnews.com/naval-news/2025/04/general-atomics-confirms-drone-killing-air-to-air-laser-is-in-development/"},
    {s:"Defense News (Apr 24 2026)", t:"The US military wants a fleet of missile-killing laser drones", u:"https://www.defensenews.com/industry/techwatch/2026/04/24/the-us-military-wants-a-fleet-of-missile-killing-laser-drones/"},
    {s:"GlobalSecurity — SBL", t:"Space-Based Laser (SBL) / Zenith Star", u:"https://www.globalsecurity.org/space/systems/sbl.htm"},
    {s:"Laser Wars (Jun 4 2026)", t:"Pulse #001: Pentagon still dreaming of space-based lasers", u:"https://www.laserwars.net/p/pulse-001-star-wars-german-laser-robot"},
    {s:"C4ISRNET (Jun 16 2021)", t:"The Space Force wants to use directed energy for space superiority", u:"https://www.c4isrnet.com/battlefield-tech/space/2021/06/16/the-space-force-wants-to-use-directed-energy-weapons-for-space-superiority/"},
    {s:"Task & Purpose (Mar 2025)", t:"The Space Force wants orbital laser weapons", u:"https://taskandpurpose.com/news/space-force-orbital-laser-weapons/"},
    {s:"Federal News Network (Apr 2026)", t:"White House seeks $17.5B for Golden Dome", u:"https://federalnewsnetwork.com/budget/2026/04/white-house-seeks-17-5-billion-for-golden-dome-but-most-funding-hinges-on-reconciliation/"},
    {s:"Breaking Defense (Nov 2025) — SBI", t:"Space Force awards first space-based boost-phase interceptor prototypes", u:"https://breakingdefense.com/2025/11/golden-dome-space-force-awards-first-space-based-boost-phase-interceptor-prototype-contracts/"},
    {s:"Air & Space Forces Mag (Dec 9 2025)", t:"Space Force eyes space-based interceptors for midcourse", u:"https://www.airandspaceforces.com/space-force-space-based-interceptors-midcourse/"},
    {s:"Laser Wars (Mar 28 2026)", t:"Here's the Status of Every Known US Military Laser Weapon", u:"https://www.laserwars.net/p/us-military-laser-weapons-programs-list"},
    {s:"Laser Wars (Apr 2026) — JLWS", t:"What We Know About the New Joint Laser Weapon System", u:"https://www.laserwars.net/p/army-navy-joint-laser-weapon-system-funding"},
    {s:"Laser Wars (Mar 16 2026)", t:"The Pentagon Wants to Field Laser Weapons at Scale Within 3 Years", u:"https://www.laserwars.net/p/us-military-laser-weapons-fielding-timeline"}
  ],

  /* Headline funding cards on the Overview tab */
  FUNDING: [
    {lab:"Total DoD DE RDT&E", big:"&gt;$2.0B", delta:'FY2027 request · <span class="up">▲</span> ~2× the ~$1B/yr of the last 5 years',
     ctx:"The official headline is &gt;$2B. By one Laser Wars estimate, the DE-<i>specific</i> program elements sum to ≈$950M (vs ≈$442M in FY2026). FY25 unclassified DE req was $789.7M (down from $1.1B appropriated in FY24)."},
    {lab:"Golden Dome DE", big:"$452M", delta:'FY2027 RDT&E · <span class="up">▲</span> &gt;3× the $142M enacted',
     ctx:"For development, integration & assessment of DE for Golden Dome — more than triple the <b>$142M enacted for Golden Dome DE under the July 2025 OBBBA reconciliation act</b> (P.L. 119-21). OBBBA also carried ~$250M for DE R&amp;D more broadly. Like that prior funding, the $452M is reconciliation-reliant, separate from the base budget."},
    {lab:"Army — SHORAD/C-UAS DE line", big:"$994.1M", delta:'FY2027 · <span class="up">▲</span> from $693.4M',
     ctx:"Bundled line covering DE (E-HEL, AMP-HEL), handheld, and kinetic/non-kinetic interceptors — not pure laser $$."},
    {lab:"Navy DE & electric weapons", big:"$94M", delta:'FY2027 RDT&E · <span class="up">▲</span> from $14.5M (FY26 req)',
     ctx:"Funds HELIOS sustainment, HELCAP upgrades, JBCS and containerized JLWS. FY25 broad Navy DE was $82.4M."},
    {lab:"Reconciliation top-up", big:"+$250M", delta:"P.L. 119-21 (OBBBA, Jul 2025)",
     ctx:"OBBBA added ~$250M for DE R&amp;D (via USD(R&amp;E)); it also enacted the $142M Golden Dome DE line that the FY2027 $452M request triples. All reconciliation-funded, separate from the base budget."},
    {lab:"Counter-drone surge (FY2027)", big:"~$2B+", delta:"across R&D + procurement",
     ctx:"Incl. $580M JIATF-401 R&D, ~$800M potential procurement, $158M critical-infrastructure, $100M World Cup 2026, $20M border. Context: $1.5T FY27 defense topline (CSIS)."}
  ],

  /* FY2027 DoD Budget Request — directed-energy detail (drives the "FY2027 Budget" tab) */
  BUDGET: {
    fy: "FY2027",
    released: "April 2026 (delayed from the usual February)",
    intro: "The FY2027 President's Budget request is the inflection point for U.S. directed energy: DE-specific RDT&amp;E program elements roughly double, a dedicated $452M Golden Dome directed-energy line appears, and the Navy's DE account jumps ~6×. The figures below are open-source readings of the request — service \"DE\" lines frequently bundle adjacent counter-UAS and interceptor funding, so always confirm against the official justification books linked at the bottom of this page.",
    topline: [
      {k:"DE-specific RDT&amp;E (Laser Wars est.)", v:"≈ $950M", note:"Laser Wars' estimate summing the named DE program elements (vs ≈$442M in FY26) — narrower than the official &gt;$2B headline."},
      {k:"DoD-wide DE RDT&amp;E (broad)", v:"&gt; $2B", note:"Wider tally that folds in DE-inclusive counter-UAS / IFPC / M-SHORAD lines. Both figures are correct at different scopes."},
      {k:"Golden Dome directed energy", v:"$452M", note:"DE \"System Development, Integration &amp; Assessment\" — more than triple the $142M enacted for Golden Dome DE under the July 2025 OBBBA reconciliation act."},
      {k:"Golden Dome (total, all layers)", v:"≈ $17.5B", note:"Mostly kinetic (space-based interceptors); much of it hinges on reconciliation funding."},
      {k:"Navy Directed Energy &amp; Electric Weapons", v:"$94.825M", note:"Up from $14.5M (FY26). Incl. $79.84M Surface Navy Laser Weapon System (jumpstart JLWS R&amp;D + HELIOS $4.247M sustainment + HELCAP upgrades) plus a separate $14.978M HELCAP injection."},
      {k:"OSD / USD(R&amp;E) HEL program elements", v:"$44.5M + $201M", note:"HEL Advanced Component Dev &amp; Prototyping ($44.5M, from $5.5M) + HEL Advanced Technology ($201M, from $120M). Run by JDETO; the $201M PE includes JLWS &amp; the Pulsed HEL Scaling Initiative."},
      {k:"Reconciliation (P.L. 119-21, OBBBA)", v:"+$250M", note:"For DE R&amp;D via USD(R&amp;E), enacted Jul 2025; OBBBA also enacted the $142M Golden Dome DE line. Separate from the base budget."}
    ],
    byService: [
      {s:"Army", v:"No standalone laser PE", note:"DE rides inside the M-SHORAD line ($460M, from $296M; carries AMP-HEL &amp; E-HEL RDT&amp;E), EMAM ($235M, from $63M; carries JLWS), the C-sUAS procurement line (~$994.1M) and IFPC Inc 2 (~$1.6B). Army JLWS R&amp;D ($337.8M) is profiled FY2028–FY2031 (FY2027 is $0)."},
      {s:"Navy / USMC", v:"$94.825M", note:"$79.84M Surface Navy Laser Weapon System (JLWS R&amp;D + HELIOS sustainment + HELCAP upgrades) + $14.978M HELCAP. USMC laser efforts (HELEX, MADIS) are ONR/contract-funded, not broken out."},
      {s:"Air Force", v:"≈ $92M", note:"\"Directed Energy Technology\" PE ≈ $92M (down from $96M); \"Directed Energy Prototyping\" PE zeroed ($0). Covers AFRL HPM/HEL S&amp;T (THOR / Mjölnir lineage)."},
      {s:"OSD / USD(R&amp;E)", v:"≈ $245.5M HEL PEs", note:"Defense-wide HEL component-prototype + advanced-technology PEs, run by JDETO. Funds HELSI (nLIGHT scaling toward megawatt-class; Lockheed toward 500 kW), JLWS, and the new Pulsed HEL Scaling Initiative."},
      {s:"MDA", v:"$452M Golden Dome DE", note:"Directed-energy missile-defense development, integration &amp; assessment."},
      {s:"Space Force / SDA · DARPA", v:"Not broken out", note:"No DE-specific FY2027 line items verified in open sources; DARPA total request ≈ $5.0B."}
    ],
    byProgram: [
      {p:"E-HEL (Army, 30 kW C-UAS)", v:"M-SHORAD line ($460M)", note:"~$25M/unit, up to ~24 planned; RDT&amp;E under the M-SHORAD item. Navy adds $4.82M to marinize it, plus a $2.5M FY27 NDAA chairman's-mark \"Containerized Maritime HEL.\""},
      {p:"JLWS / EMAM (Army + Navy)", v:"$675.93M R&amp;D thru FY2031", note:"Army $337.8M (FY28–31; FY27 $0, closing out IFPC-HEL first) + Navy $243.3M. FY27 Navy $79.84M Surface Navy Laser Weapon System jumpstarts it; JBCS ~$31.7M Q4 FY26; containerized JLWS ~$30M by Mar 2027. Likely Lockheed."},
      {p:"IFPC-HPM \"Leonidas\" (Army)", v:"Within IFPC Inc 2 (~$1.6B)", note:"Recent Gen II award $43.55M (Jul 2025)."},
      {p:"HELIOS (Navy)", v:"$225.4M obligated", note:"FY27 R&amp;D sustainment only ($4.247M, inside the $79.84M line); containerized-HELIOS ~$5M NDAA chairman's-mark add. No procurement."},
      {p:"HELCAP (Navy counter-ASCM)", v:"$206M obligated", note:"FY27 +$14.978M to upgrade the test bed in support of future JLWS testing."},
      {p:"Golden Dome DE (MDA)", v:"$452M", note:"Non-kinetic missile-defense layer (HEL / HPM)."},
      {p:"JIATF-401 counter-drone pilot", v:"≈ $580M RDT&amp;E", note:"Five-base directed-energy C-UAS pilot (DE share unspecified)."}
    ],
    reconciliation: "The \"&gt;$2B\" (DE-inclusive) headline and the ≈$950M (DE-specific, a Laser Wars estimate) differ only in scope. On reconciliation: the July 2025 OBBBA act (P.L. 119-21) <b>enacted the $142M Golden Dome DE line</b> that the FY2027 $452M request more than triples, and OBBBA <b>also</b> carried ~$250M for DE R&amp;D more broadly (via USD(R&amp;E)). Both the $142M and the $452M are reconciliation-reliant, separate from the base budget. Service \"DE\" lines frequently bundle adjacent counter-UAS and interceptor money.",
    docs: [
      {t:"DoD FY2027 Budget Justification Materials (hub)", u:"https://comptroller.war.gov/Budget-Materials/FY2027BudgetJustification/", d:"Canonical entry point — links to every service/agency RDT&amp;E (R-2) and procurement (P-40) justification book. (Verified live.)"},
      {t:"FY2027 Budget Request Overview Book (PDF)", u:"https://comptroller.war.gov/Portals/45/Documents/defbudget/FY2027/FY2027_Budget_Request_Overview_Book.pdf", d:"DoD-wide topline and the directed-energy / Golden Dome narrative."},
      {t:"FY2027 RDT&amp;E Programs (R-1) (PDF)", u:"https://comptroller.war.gov/Portals/45/Documents/defbudget/FY2027/FY2027_r1.pdf", d:"Every RDT&amp;E program-element line with dollar figures."},
      {t:"FY2027 Procurement Programs (P-1) (PDF)", u:"https://comptroller.war.gov/Portals/45/Documents/defbudget/FY2027/FY2027_p1.pdf", d:"Procurement line numbers (e.g., where ODIN-type DE crosses into OPN)."},
      {t:"Defense-wide / OSD RDT&amp;E justification (PDF)", u:"https://comptroller.war.gov/Portals/45/Documents/defbudget/FY2027/budget_justification/pdfs/03_RDT_and_E/RDTE_OSW_PB_2027.pdf", d:"Where the OSD HEL program elements ($44.5M, $201M) sit."},
      {t:"DARPA RDT&amp;E justification (PDF)", u:"https://comptroller.war.gov/Portals/45/Documents/defbudget/FY2027/budget_justification/pdfs/03_RDT_and_E/RDTE_Vol1_DARPA_MasterJustificationBook_PB_2027.pdf", d:"DARPA DE-relevant S&amp;T program elements."},
      {t:"Army budget materials (asafm.army.mil)", u:"https://www.asafm.army.mil/Budget-Materials/", d:"Army FY2027 books — M-SHORAD, C-sUAS and IFPC DE content (RDTE Vol 2, Budget Activity 4B)."},
      {t:"Navy FMB — FY2027", u:"https://www.secnav.navy.mil/fmc/fmb/Pages/Fiscal-Year-2027.aspx", d:"Navy justification books — HELIOS / HELCAP / Surface Navy Laser Weapon System PEs."},
      {t:"Air Force FY2027 President's Budget (SAF/FMB)", u:"https://www.saffm.hq.af.mil/FM-Resources/Budget/Air-Force-Presidents-Budget-FY27/", d:"Air Force justification books — AFRL HPM/HEL program elements."},
      {t:"CRS R46925 — DE Weapons: Background &amp; Issues", u:"https://www.congress.gov/crs-product/R46925", d:"Congressional primer on DoD directed-energy programs and funding."},
      {t:"CRS IN12576 — Golden Dome reconciliation funding", u:"https://www.congress.gov/crs-product/IN12576", d:"On the $250M directed-energy top-up in P.L. 119-21 (OBBBA)."}
    ],
    caveat: "Most figures are read from the April 3 'skinny' budget request (Laser Wars analysis); the full justification books (released ~April 21) refine them. Links point to official Comptroller and service budget portals — the justification hub is the stable entry point; deep-link PDFs may move, and .mil/.gov portals may need a normal browser."
  },

  DATA: {
    army:[
      {name:"E-HEL", start:2025, match:["e-hel","enduring high energy laser"], code:"Enduring High Energy Laser", status:"new", power:"30 kW (modular)",
       blurb:"Army's first planned DE program of record — a modular counter-UAS laser replacing DE M-SHORAD.",
       cost:["RDT&amp;E sits under the Army's M-SHORAD line ($460M); procurement under the C-sUAS line (~$994.1M FY2027).",
             "Navy adds $4.82M for marinization, plus a $2.5M FY27 NDAA chairman's-mark 'Containerized Maritime HEL.'",
             "Plan: procure 2 in FY2026, 2 in FY2027; produce &amp; rapidly field up to 24 systems over ~5 years."],
       timeline:[{d:"Oct 30 2025",e:"RFI issued to inform a production effort"},
                 {d:"Q2 FY2026",e:"Competitive source selection; first prototype expected"},
                 {d:"Q4 FY2026",e:"Production decision targeted (would make it the Army's first DE PoR)"},
                 {d:"End FY2027",e:"First initial-procurement units delivered"}],
       suppliers:"TBD via open competition — bidders include AeroVironment (LOCUST), HII (which won an Army open-architecture HEL OTA in 2025) and other DE primes.",
       news:[{d:"Jun 2026",t:"Still in source-selection — no vendor down-select announced publicly; production decision still targeted Q4 FY2026."},
             {d:"2026",t:"Geared specifically at small UAS / one-way-attack drones; succeeds the shelved 50 kW DE M-SHORAD."},
             {d:"2025",t:"Army framed E-HEL as a deliberately 'enduring,' modular design to avoid the obsolescence that dogged earlier prototypes."}],
       note:"<b>Correction vs original chart:</b> E-HEL is a <b>30 kW counter-drone</b> laser, <u>not</u> '50–300 kW TBD.' The higher-power (150→300 kW) counter-cruise-missile role belongs to JLWS. E-HEL is also further along than 'requirements phase' — it is at source-selection / production-decision, and it predates the March 2026 CRS report (RFI was Oct 2025).",
       src:["DefenseScoop (Nov 3 2025)","Breaking Defense (Nov 2025)","Breaking Defense (Mar 2025) — HII HEL","Defense News (Apr 28 2026)"]},

      {name:"AMP-HEL", start:2025, match:["amp-hel","locust"], code:"Army Multi-Purpose High Energy Laser", status:"active", power:"20 kW (LOCUST)",
       blurb:"NOT in the original chart. Vehicle-mounted 20 kW LOCUST laser — the spearhead of the domestic 'laser dome.'",
       cost:["BlueHalo $45.7M contract (Apr 2024); ~$3 per engagement (vs millions per missile interceptor).",
             "Four delivered: two on the M1301 ISV (late 2024) and two on JLTVs (Dec 2025). Initial Army requirement: 24 systems."],
       timeline:[{d:"Apr 2024",e:"BlueHalo awarded $45.7M to build AMP-HEL (20 kW LOCUST) for the M1301 Infantry Squad Vehicle"},
                 {d:"Late 2024",e:"First two AMP-HEL delivered on ISVs (shown at Fort Sill Fires Symposium, Apr 2025)"},
                 {d:"Dec 2025",e:"Two more delivered on JLTVs (four total)"},
                 {d:"Feb 2026",e:"CBP used an AMP-HEL at the border without FAA coordination (El Paso airspace shutdown); days later troops downed a drone that proved to be a friendly CBP drone — the first publicly confirmed US laser kill"},
                 {d:"Mar 2026",e:"Pentagon/FAA test a JLTV-mounted AMP-HEL at White Sands (Boeing 767 fuselage, no damage)"},
                 {d:"Apr 10 2026",e:"FAA–Dept. of War landmark safety agreement clears counter-drone lasers around civil aviation"},
                 {d:"May 27 2026",e:"SecArmy Dan Driscoll fires AMP-HEL on an ISV, downing a drone"}],
       suppliers:"AeroVironment (AV) — formerly BlueHalo — LOCUST Laser Weapon System; platforms: GM Defense Infantry Squad Vehicle (M1301 ISV) and Oshkosh JLTV.",
       news:[{d:"Jun 2026",t:"Cited as the only laser cleared under the first FAA–Dept. of War counter-drone laser airspace agreement (per AeroVironment)."},
             {d:"Feb 2026",t:"Scored the US military's first publicly confirmed laser weapon kill — a friendly-fire downing of a CBP drone at the border (per Laser Wars)."},
             {d:"2026",t:"Named among systems for the JIATF-401 five-base directed-energy C-UAS pilot; SecArmy demoed it at White Sands."}],
       note:"<b>New program</b> absent from the source charts. Same 20 kW LOCUST family as P-HEL, but vehicle-mounted (ISV and JLTV); four are operational. Laser Wars credits AMP-HEL with the first confirmed (friendly-fire) US laser kill.",
       src:["Laser Wars (Mar 28 2026)","AeroVironment (Jun 3 2026)","Military Times (Apr 13 2026)","DefenseScoop (Mar 16 2026)"]},

      {name:"JLWS", start:2026, match:["jlws","joint laser"], code:"Joint Laser Weapon System", status:"new", power:"150 kW → ≥300 kW (JBCS: 300–500 kW)",
       blurb:"Joint Army–Navy successor to IFPC-HEL — a containerized counter-cruise-missile laser inside Golden Dome.",
       cost:["Combined Army+Navy vision: <b>$675.93M</b> R&amp;D through FY2031.",
             "Army: $337.8M (FY2028–FY2031); FY2027 is $0 — the Army closes out IFPC-HEL first ($51M prior mandatory JLWS funding came via the OBBBA reconciliation act under EMAM).",
             "Navy: +$243.3M R&amp;D through FY2031; the FY2027 jumpstart sits inside the $79.84M Surface Navy Laser Weapon System line.",
             "Near-term contracts: $31.7M for the Joint Beam Control System (JBCS) as soon as Q4 FY2026; $30M to procure/test a containerized JLWS by Mar 2027."],
       timeline:[{d:"2026",e:"Army closes out IFPC-HEL first; takes delivery of the first 300 kW IFPC-HEL prototype to divest into JLWS"},
                 {d:"Q4 FY2026",e:"Navy plans first JBCS development contracts ($31.7M)"},
                 {d:"Mar 2027",e:"Containerized JLWS procurement/testing contracts ($30M)"},
                 {d:"FY2028+",e:"Army funding ramps ($337.8M FY28–31); scale toward ≥300 kW"}],
       suppliers:"Lockheed Martin is the likely prime (technical lead on both HELIOS and IFPC-HEL; revealed Aug 2025 it is already building a containerized HELIOS). Budget lines: Army Expanded Mission Area Missile (EMAM); Navy Surface Navy Laser Weapon System.",
       news:[{d:"Jun 2026",t:"Part of a DoD push to demonstrate a battle-ready laser weapon by summer 2028 under Golden Dome."},
             {d:"Apr 2026",t:"Defense News laid out the joint funding profile; the system starts at a containerized 150 kW with a path to 300 kW+."},
             {d:"Mar 2026",t:"Confirmed as the destination for IFPC-HEL's divested prototype and lessons learned."}],
       note:"<b>Name clarification:</b> rendered both 'Joint Laser <i>Weapon</i> System' (Defense News, original chart) and 'Joint Laser <i>Warfighting</i> System' (Military Times) — same JLWS acronym. Power detail (150→300 kW + JBCS) is an enrichment over the original 'counter-cruise-missile' note.",
       src:["Defense News (Apr 28 2026)","Laser Wars (Apr 2026) — JLWS","Military Times (Jun 2 2026)","Military Times (Mar 23 2026)"]},

      {name:"IFPC-HEL", start:2022, match:["ifpc-hel","valkyrie"], code:"\"Valkyrie\"", status:"cancelled", power:"300 kW",
       blurb:"The most powerful U.S. laser built to date — cancelled in 2026 rather than transitioned to a program of record.",
       cost:["$220.8M Other Transaction Authority agreement (Jul 2023); Lockheed contract for four systems (Oct 2023).",
             "Army planned to cut ~$4.8B from future spending ($327M in FY25); reduced from four prototypes to a single prototype."],
       timeline:[{d:"Sep 2022",e:"300 kW demonstrator delivered (HEL-TVD lineage)"},
                 {d:"Jul 2023",e:"$220.8M OTA for 4 prototypes (Dynetics/Lockheed)"},
                 {d:"Jan 2026",e:"Army still publicly planned a program-of-record transition in FY2025"},
                 {d:"Mar 9 2026",e:"CRS report reveals the Army has dropped the PoR transition"},
                 {d:"Summer 2026",e:"Developmental testing at Dugway Proving Ground, UT"},
                 {d:"~Sep 2026",e:"Final prototype delivered, then 'divested as a fielding candidate' to inform JLWS"}],
       suppliers:"Dynetics (a Leidos company) prime / system integrator; Lockheed Martin 300 kW laser; truck-and-trailer mounted.",
       news:[{d:"Mar 2026",t:"\"Results from the lab and test ranges were very different from the tactical environment\" — the recurring theme behind the shelving."},
             {d:"2026",t:"Prototype undergoing final lab testing at Lockheed's New Jersey facility before Dugway."}],
       note:"Consistent with the original chart (SHELVED). Added detail: Sept 2022 demonstrator, Dugway summer 2026, Sept 2026 delivery, explicit 'divest to JLWS.' CRS source date is <b>March 9, 2026</b>.",
       src:["Laser Wars (Mar 28 2026)","Military Times (Mar 23 2026)","CRS IF12421 (Jan 2026)","Defense News (Apr 28 2026)"]},

      {name:"DE M-SHORAD", start:2021, match:["de m-shorad","m-shorad","guardian"], code:"\"Guardian\"", status:"cancelled", power:"50 kW",
       blurb:"Stryker-mounted 50 kW laser; the first fielded DE maneuver-SHORAD — now cancelled, with all four prototypes demilitarized.",
       cost:["Took a ~$38M cut in FY25 and a ~$186M out-year cut.",
             "A platoon's worth (4 systems) was built and sent to CENTCOM."],
       timeline:[{d:"Late 2023",e:"Four 'Guardian' systems delivered (RTX, Stryker-mounted)"},
                 {d:"Mar 2024",e:"Deployed to CENTCOM for real-world testing; soldiers 'not impressed'"},
                 {d:"Jun 2025",e:"GAO: PoR transition delayed 2 years, 'not mature enough'; Army eyed dropping the Stryker"},
                 {d:"Jun 2025",e:"All four prototypes demilitarized after a Fort Sill live-fire (one to the ADA Training Support Facility)"},
                 {d:"Mar 2026",e:"DOT&E confirms the Army is 'no longer pursuing DE M-SHORAD as a program of record'; folded into E-HEL"}],
       suppliers:"RTX (Raytheon) laser; Kord Technologies integrator; platform: Stryker A1.",
       news:[{d:"2024",t:"Army acquisition chief Doug Bush: feedback 'not overwhelmingly positive'; the 50 kW power level was hard to cool and sustain on a constantly-moving vehicle."},
             {d:"2026",t:"Officially dead — superseded by the Enduring HEL (E-HEL)."}],
       note:"<b>Correction:</b> not merely shelved — officially <b>cancelled</b>; all four prototypes demilitarized (Jun 2025, Fort Sill) per DOT&E. Delivery now dated to late 2023.",
       src:["Laser Wars (Mar 28 2026)","Military Times (Mar 23 2026)","CRS R46925 (Jul 11 2024)"]},

      {name:"IFPC-HPM", start:2023, match:["ifpc-hpm","leonidas","epirus"], code:"\"Leonidas\"", status:"active", power:"HPM (GaN AESA microwave)",
       blurb:"Epirus high-power microwave for swarm defeat — the Army DE effort closest to a program of record.",
       cost:["First four IFPC-HPM systems: ~$66M.",
             "Gen II contract: $43.55M (Jul 17 2025, RCCTO) for two Gen II systems + tests/spares."],
       timeline:[{d:"2023–24",e:"Four Gen I systems delivered; new-equipment training & developmental testing complete"},
                 {d:"Jul 2025",e:"$43.55M Gen II award (2 systems)"},
                 {d:"Aug–Sep 2025",e:"Gen II system deliveries"},
                 {d:"Oct 2025",e:"Test & evaluation at NAWS China Lake, CA"}],
       suppliers:"Epirus, Inc. (Leonidas, GaN-based solid-state AESA microwave).",
       news:[{d:"Dec 2025",t:"Reported to have downed a 49-drone swarm in a single pulse and defeated fiber-optic-guided UAS in testing."},
             {d:"2025",t:"Gen II promises >2× effective range, ~+30% power, high-density batteries, long-pulse / high-duty burst modes."},
             {d:"2025",t:"Informing a potential program of record under the Army Transformation Initiative."}],
       note:"Matches the original chart ($66M + $43.55M Gen II). Verified contract value $43,551,060.",
       src:["Epirus (Jul 17 2025)","The War Zone — Leonidas","CRS R46925 (Jul 11 2024)"]},

      {name:"P-HEL", start:2022, match:["p-hel","palletized high energy laser"], code:"Palletized High Energy Laser", status:"active", power:"20 kW (LOCUST)",
       blurb:"The Army's surprise operational win — a palletized 20 kW LOCUST laser quietly deployed overseas.",
       cost:["Low-cost, rapidly fielded; exact value not broken out publicly. ~$3/shot economics like AMP-HEL."],
       timeline:[{d:"~2022–23",e:"Deployed overseas for base defense"},
                 {d:"2024–25",e:"Reported 'proving successful' against UAS; LOCUST also tested from aircraft carriers"}],
       suppliers:"AeroVironment (AV) — formerly BlueHalo — LOCUST Laser Weapon System (palletized).",
       news:[{d:"2025",t:"BlueHalo's LOCUST became 'first to operationally field' a DE laser; AV completed its BlueHalo acquisition (~mid-2025)."},
             {d:"2026",t:"Its success underwrote momentum for AMP-HEL and E-HEL."}],
       note:"<b>Supplier update:</b> 'BlueHalo LOCUST' is now an <b>AeroVironment</b> product (AV acquired BlueHalo; merger agreement Nov 2024, closed ~H1 2025).",
       src:["AeroVironment / BlueHalo","CRS R46925 (Jul 11 2024)"]},

      {name:"Power-scaling lineage", start:2014, match:["hel-tvd","helmtt"], code:"HELMTT → HEL-TVD → IFPC-HEL", status:"concept", power:"10 → 100 → 300 kW",
       blurb:"The technology ladder behind the Army's high-power lasers — each rung a step up in beam power.",
       cost:["S&amp;T / demonstrator funding; not procurement programs."],
       timeline:[{d:"2010s",e:"HELMTT — 10 kW High Energy Laser Mobile Test Truck"},
                 {d:"~2019–22",e:"HEL-TVD — 100 kW High Energy Laser Tactical Vehicle Demonstrator"},
                 {d:"2022+",e:"IFPC-HEL — 300 kW (now shelved → JLWS)"}],
       suppliers:"Various (Lockheed Martin / Dynetics on the higher rungs).",
       news:[{d:"—",t:"Also feeds the concept of lasers on next-generation combat vehicles (360°/active protection; fielding target ~2035; key decisions ~2025)."}],
       note:"Lineage/concept, unchanged from the original chart.",
       src:["CRS R46925 (Jul 11 2024)"]}
    ],

    navy:[
      {name:"HELIOS", start:2018, match:["helios","uss preble"], code:"SNLWS Inc. 1", status:"fielded", power:"60 kW-class (designed to grow to 120–150 kW)",
       blurb:"The Navy's flagship shipboard HEL — Aegis-integrated on USS Preble, now downing drones in real tests.",
       cost:["<b>$225.4M obligated</b> to date (2018 Lockheed contract ceiling $1.1B, with options for up to 14 units that were never exercised).",
             "FY2027: R&amp;D sustainment only ($4.247M, inside the Navy's $79.84M Surface Navy Laser Weapon System line); a containerized HELIOS is a ~$5M FY27 NDAA chairman's-mark add (plus a separate $2.5M to marinize E-HEL). No procurement."],
       timeline:[{d:"2018",e:"Lockheed Martin awarded a contract with a $1.1B ceiling (options for 14 units never exercised)"},
                 {d:"2022",e:"Integrated aboard USS Preble (DDG-88), Aegis-tied"},
                 {d:"Feb 2025",e:"Vivid photo of HELIOS disabling a drone target"},
                 {d:"May 2025",e:"Acting CNO Adm. Kilby tells Congress HELIOS reached only ~1/3 of intended power in testing (Lockheed later disputes)"},
                 {d:"Jan 2026",e:"Lockheed CEO: HELIOS 'neutralized four drone threats' in an at-sea counter-UAS demo"},
                 {d:"~FY29",e:"Remains on Preble for fleet testing & sustainment"}],
       suppliers:"Lockheed Martin (spectrally-combined fiber laser, integrated optical dazzler + ISR).",
       news:[{d:"May 2026",t:"Lawmakers propose a ~$5M containerized HELIOS (FY27 NDAA chairman's mark) — a 'last ride' that would feed the JLWS design."},
             {d:"2025–26",t:"Power-output controversy: acting CNO said ~1/3 power (May 2025); Lockheed insisted full power (Aug 2025); CEO cited a four-drone at-sea kill (Jan 2026)."}],
       note:"<b>Power dispute (kept):</b> delivered as a 60 kW-class system. Growth target is cited as <b>120 kW</b> (CRS R46925, 2026 DEHEL report) or <b>150 kW</b> (CRS R44175, Jan 2026; Lockheed). Per Laser Wars, ~$225.4M has been obligated and HELIOS reached only ~1/3 power in 2025 testing (Lockheed disputes).",
       src:["CRS R44175","The War Zone (TWZ)","Laser Wars (May 30 2026)","Laser Wars (Mar 28 2026)","Defense News (Apr 28 2026)"]},

      {name:"ODIN", start:2019, match:["odin","optical dazzling"], code:"Optical Dazzling Interdictor, Navy", status:"fielded", power:"Low-power dazzler",
       blurb:"The only DE system to cross fully into procurement + sustainment — a counter-ISR 'dazzler' on destroyers.",
       cost:["&gt;$200M spent to date; the lone DE system to reach procurement (OPN) + sustainment (O&amp;MN).",
             "FY2027: the 'Directed Energy Systems' procurement line is zeroed out (from $3M in FY26) — the eight installed systems now 'inform' future prototyping / PoR efforts."],
       timeline:[{d:"2019–22",e:"Fielded on Arleigh Burke Flt IIA destroyers"},
                 {d:"Nov 2024",e:"ODIN-armed USS Spruance & USS Stockdale targeted by Houthi drones/missiles exiting the Red Sea (Op. Prosperity Guardian)"},
                 {d:"2025",e:"Eight units installed across the fleet (incl. USS Spruance, USS Stockdale)"},
                 {d:"Feb 2026",e:"USS Spruance's ODIN visible in photos as the ship launched a Tomahawk at Iran (Op. Epic Fury)"}],
       suppliers:"Navy-designed (NSWC Dahlgren); produced by VTG Defense.",
       news:[{d:"2026",t:"Confirmed aboard USS Spruance (DDG-111) during Operation Epic Fury — Laser Wars notes the NY Post misidentified it as HELIOS; it is ODIN."},
             {d:"2026",t:"With FY27 procurement zeroed, ODIN's eight units 'inform' future DE prototyping and programs of record."}],
       note:"<b>Acronym:</b> 'Optical Dazzling <b>Interdictor</b>, Navy' (Navy budget language / R44175). <b>Supplier update:</b> Navy-designed but produced by contractor <b>VTG Defense</b> (Laser Wars). Dropped USS Dewey (named only by an earlier source; Laser Wars cites Spruance & Stockdale).",
       src:["CRS R44175","Laser Wars (Mar 28 2026)","DefenseScoop (Feb 18 2026)","Laser Wars (Mar 5 2026)"]},

      {name:"HELCAP", start:2024, match:["helcap"], code:"High Energy Laser Counter-ASCM Program", status:"counter", power:"300 kW+ source",
       blurb:"The Navy's high-power counter-anti-ship-cruise-missile testbed — solving beam control, not yet a weapon.",
       cost:["~$206M obligated to date; RDT&amp;E, non-program-of-record.","FY2027: a separate $14.978M injection to upgrade the test bed in support of future JLWS testing."],
       timeline:[{d:"2024",e:"300 kW source (adapted from HELSI) readied for intercept tests"},
                 {d:"FY2025",e:"Demonstrations vs surrogate ASCMs at White Sands (DETAM campaign, Laser Weapon Testbed)"},
                 {d:"FY2026",e:"Standalone program completes; test bed upgraded 'as appropriate' to support JLWS testing"}],
       suppliers:"Navy (ONR / NSWC) with HELSI-derived laser source; beam-control / atmospheric-turbulence focus.",
       news:[{d:"2026",t:"The HEL source and beam-control lessons hand off to the joint JLWS; the test bed is being upgraded to support JLWS testing rather than fielded as a standalone weapon."}],
       note:"Matches the original chart. The FY2027 $14.978M is explicitly for upgrading the test bed in support of JLWS testing (per the Navy budget request).",
       src:["optics.org / Naval News","Laser Wars (Apr 2026) — JLWS","CRS R44175"]},

      {name:"Songbow", start:2025, match:["songbow"], code:"Coherent A&D", status:"demo", power:"400 kW-class (4 × 50 kW pulsed-fiber)",
       blurb:"A new 400 kW pulsed-fiber laser effort aimed at swarms, cruise missiles and even hypersonic glide vehicles.",
       cost:["$29,981,651 cost-plus-fixed-fee (Jun 10 2025).",
             "20-month base period + 11- and 18-month options (may run concurrently)."],
       timeline:[{d:"Jun 10 2025",e:"Contract awarded to Coherent Aerospace & Defense (Murrieta, CA)"},
                 {d:"Jan 2027",e:"Scheduled completion (full DE subsystem: beam director + precision optics)"}],
       suppliers:"Coherent Aerospace &amp; Defense — coherently combining four-plus 50 kW pulsed-fiber modules.",
       news:[{d:"2025",t:"Aims at drone swarms, cruise missiles and hypersonic glide vehicles 'at the speed of light'; also remote sensing / target illumination."}],
       note:"<b>Update vs original chart:</b> no longer 'single-source' — Songbow is corroborated by multiple outlets (Naval News, optics.org, defense press). Figures verified ($29.98M; Jan 2027).",
       src:["optics.org / Naval News"]},

      {name:"BBG(X) battleship", start:2025, match:["bbg","golden fleet","trump-class"], code:"\"Trump-class\" guided-missile battleship", status:"platform", power:"2 lasers × 300 or 600 kW",
       blurb:"The Navy's future destination for high-power lasers — a large, power-rich combatant ('Golden Fleet').",
       cost:["Navy planning exceeds <b>$17B</b> for the first unit (lead ship <b>USS Defiant</b>).",
             "FY2027: $1B advance procurement; ~$16.47B buy in FY2028; ~3 hulls (~$43.5B) through FY2031."],
       timeline:[{d:"Dec 22 2025",e:"Trump administration announces the new battleship class"},
                 {d:"May 2026",e:"Navy confirms nuclear propulsion; lead ship named USS Defiant"},
                 {d:"FY2027",e:"$1B advance procurement requested"},
                 {d:"FY2028",e:"First hull procured (~$16.47B)"},
                 {d:"2030s",e:"Armed with two lasers (300 or 600 kW each — Caudle floats megawatt-class), hypersonics & rail guns"}],
       suppliers:"TBD (program early). Zumwalt-class destroyers floated as near-term laser power-generation testbeds.",
       news:[{d:"May 2026",t:"Nuclear propulsion confirmed (USNI / DefenseScoop); CNO Adm. Caudle frames the ship as the 'forcing function' to scale megawatt-class shipboard lasers."},
             {d:"Feb 2026",t:"Caudle &amp; VADM McLane cast the battleship as a way to scale lasers across the fleet; 600 kW could counter some ASCMs."}],
       note:"Matches the original chart (Dec 22 2025; 300/600 kW). Added: confirmed nuclear propulsion, lead ship USS Defiant, FY2027 $1B advance procurement / FY2028 buy, 'Golden Fleet' framing.",
       src:["DefenseScoop (Feb 18 2026)","USNI News (May 11 2026)","DefenseScoop (May 19 2026)","CRS R44175"]},

      {name:"SSL-TM → LWSD", start:2019, match:["lwsd","uss portland","crimson dragon"], code:"Laser Weapon System Demonstrator", status:"demo", power:"150 kW",
       blurb:"The 150 kW shipboard demonstrator that downed a UAV from USS Portland in 2020 — mothballed, then brought back from the dead to kill four drones in 2025.",
       cost:["RDT&amp;E demonstrator; ~$50M was spent deinstalling it (FY2023) before restoration began in early 2025."],
       timeline:[{d:"2019–20",e:"Installed on USS Portland (LPD-27); downed a UAV in 2020"},
                 {d:"FY2023",e:"Deinstalled (~$50M)"},
                 {d:"Mar 2025",e:"Restoration begins"},
                 {d:"Sep 2025",e:"Reactivated for exercise 'Crimson Dragon' — shoots down four drones"}],
       suppliers:"Northrop Grumman (LWSD Mk 2 Mod 0).",
       news:[{d:"Mar 2026",t:"Defense News: the one-of-a-kind LWSD was 'brought back from the dead' and downed four drones in Crimson Dragon (Sept 2025)."}],
       note:"<b>Correction vs prior data:</b> not retired — reactivated in 2025; status changed retired → demo.",
       src:["Defense News (Mar 31 2026)","CRS R44175"]},

      {name:"Layered Laser Defense", start:2022, match:["layered laser defense","layered laser"], code:"LLD", status:"demo", power:"150 kW",
       blurb:"A Lockheed demo laser that killed a subsonic-cruise-missile analog — proof of principle, not to be fielded.",
       cost:["~$22M (demonstration)."],
       timeline:[{d:"2022",e:"Defeated a subsonic cruise-missile target analog in testing"}],
       suppliers:"Lockheed Martin.",
       news:[{d:"—",t:"Demonstration only; informed counter-cruise-missile laser requirements."}],
       note:"Unchanged from the original chart.",
       src:["CRS R44175"]},

      {name:"RHEL", start:2016, match:["ruggedized hel"], code:"Ruggedized HEL", status:"retired", power:"—",
       blurb:"A ruggedized HEL effort that fed an 'alternate laser design'; completed and no longer active.",
       cost:["RDT&amp;E; completed."],
       timeline:[{d:"—",e:"Completed; fed an alternate laser design"}],
       suppliers:"Navy.",
       news:[{d:"—",t:"No longer an active line."}],
       note:"Unchanged from the original chart.",
       src:["CRS R44175"]},

      {name:"LOCUST (shipboard)", start:2025, match:["locust","george h.w. bush","cvn-77","carrier laser"], code:"AeroVironment LOCUST Laser Weapon System", status:"demo", power:"30 kW (palletized)",
       blurb:"The first laser ever fired from a U.S. aircraft carrier — AeroVironment's roll-on/roll-off LOCUST, the Navy sibling of the Army's P-HEL / AMP-HEL.",
       cost:["Low-cost, rapidly fielded; value not broken out publicly. ~$3/shot economics like the Army LOCUST systems."],
       timeline:[{d:"Oct 2025",e:"Live-fire downs multiple drones from USS George H.W. Bush (CVN-77) — first carrier laser shot"},
                 {d:"Mar 2026",e:"AeroVironment unveils LOCUST X3 (20–30 kW, AI-enabled)"},
                 {d:"2026",e:"X3 testing underway; counter-UAS up to Group 3"}],
       suppliers:"AeroVironment (formerly BlueHalo) LOCUST; Navy with Army RCCTO.",
       news:[{d:"2025",t:"'First laser fired from a U.S. supercarrier' — a milestone for shipboard counter-drone DE."},
             {d:"2026",t:"LOCUST X3 announced as the next entrant in the counter-drone laser race."}],
       note:"Same LOCUST family as the Army's P-HEL (palletized) and AMP-HEL (vehicle-mounted); this entry tracks the Navy / carrier demonstrations.",
       src:["Naval News (Apr 2026)","The War Zone — LOCUST carrier","Breaking Defense (Mar 24 2026)"]},

      {name:"Project METEOR", start:2024, match:["project meteor","meteor microwave"], code:"Shipboard high-power microwave", status:"demo", power:"HPM (microwave)",
       blurb:"The Navy's first shipboard high-power microwave — a deep-magazine counter-UAS / counter-electronics weapon (HPM, not a laser).",
       cost:["~$14M (FY25) + ~$10M (FY26) RDT&amp;E."],
       timeline:[{d:"2024",e:"Open-air testing at Point Mugu"},
                 {d:"2026 (planned)",e:"First at-sea installation targeted"}],
       suppliers:"NSWC Dahlgren-led.",
       news:[{d:"2024",t:"Navy aims to put its first shipboard HPM to sea, pairing high-volume counter-swarm microwave with its lasers."}],
       note:"⚠ Single-source / older reporting (USNI, 2024) on the 2026 at-sea date — schedule unconfirmed. HPM (microwave), adjacent to the laser programs.",
       src:["USNI News (Mar 2024)"]}
    ],

    usmc:[
      {name:"HELEX", start:2022, match:["helex","high energy laser expeditionary"], code:"High Energy Laser Expeditionary", status:"demo", power:"10 kW (vehicle-mounted)",
       blurb:"The Marine Corps' ONR-sponsored 10 kW expeditionary laser — one of the ~16 US laser weapons currently operational or in testing.",
       cost:["ONR-sponsored S&amp;T; not detailed in budget documents."],
       timeline:[{d:"2022+",e:"In development under ONR; HMMWV-mounted, with plans for the JLTV"},
                 {d:"Apr 2024",e:"Downed small drones from a Humvee in testing in Arizona (WTI course)"},
                 {d:"2025",e:"Navy plans an AI-based tracking / targeting system in an upcoming live-fire demo"}],
       suppliers:"Office of Naval Research; beam director / radar via NSWC Dahlgren & Crane.",
       news:[{d:"2026",t:"Counted among the US military's ~16 operational / in-testing laser weapons (Laser Wars)."}],
       note:"⚠ Little public detail; not a budget line of record. Outlook 'hazy' per Laser Wars.",
       src:["Laser Wars (Mar 28 2026)"]},

      {name:"MADIS JLTV laser", start:2023, match:["madis","marine air defense integrated system"], code:"LOCUST on JLTV (MADIS increment)", status:"indev", power:"20 kW (LOCUST)",
       blurb:"A Marine Corps effort to adapt AV's LOCUST laser onto the JLTV for a future increment of the Marine Air Defense Integrated System (MADIS).",
       cost:["Nov 2023 USMC contract to AeroVironment (amount unspecified)."],
       timeline:[{d:"Nov 2023",e:"USMC awards AV a contract to adapt LOCUST for the JLTV under MADIS"},
                 {d:"2025–26",e:"MADIS currently fields chain guns + SAMs; lasers eyed for future increments"}],
       suppliers:"AeroVironment (LOCUST); platform: Oshkosh JLTV (MADIS).",
       news:[{d:"2026",t:"USMC officials say they are 'absolutely interested' in lasers for future MADIS increments."}],
       note:"⚠ Where it fits in MADIS is unclear; outlook 'hazy' per Laser Wars.",
       src:["Laser Wars (Mar 28 2026)"]},

      {name:"CLaWS", start:2019, match:["claws","compact laser weapon system"], code:"Compact Laser Weapon System (Boeing)", status:"cancelled", power:"2–5 kW (scalable)",
       blurb:"Boeing's compact ground laser — billed as the first ground-based laser DoD approved for warfighter use — now returned to Boeing by the Marine Corps.",
       cost:["USMC fielded five CLaWS units; returned to Boeing (Jan 2026 reporting)."],
       timeline:[{d:"~2019–22",e:"5 kW CLaWS integrated with tactical vehicles (e.g., Polaris MRZR)"},
                 {d:"Jan 2026",e:"Marine Corps returns its five CLaWS units to Boeing to 'invest in more deliberate programs of record'"}],
       suppliers:"Boeing.",
       news:[{d:"2026",t:"USMC divested CLaWS in favor of a more deliberate laser program of record."}],
       note:"Cancelled per Laser Wars.",
       src:["Laser Wars (Mar 28 2026)"]}
    ],

    af:[
      {name:"THOR", start:2019, match:["thor","tactical high-power operational responder"], code:"Tactical High-power Operational Responder", status:"demo", power:"HPM (counter-swarm)",
       blurb:"AFRL's air-base-defense microwave that disables drone swarms in a single pulse — built fast and cheap.",
       cost:["~$15–18M; built in roughly 18 months (AFRL/Wikipedia cite $18M; original chart ~$15M)."],
       timeline:[{d:"2019",e:"Initial testing begins"},
                 {d:"Apr 2023",e:"Defeats a simulated swarm at the Chestnut Test Site, Kirtland AFB"},
                 {d:"2024+",e:"Informs follow-on Mjölnir"}],
       suppliers:"AFRL with BAE Systems / Leidos / Verus Research. Ships in a 20-ft container, runs off a wall plug, ~3-hr setup; C-130 transportable.",
       news:[{d:"2023–24",t:"Swarm-defeat demo validated 'detect a cluster, pulse in nanoseconds, disable many drones' for base defense."}],
       note:"Minor cost discrepancy: original chart ~$15M; AFRL/Wikipedia state ~$18M over 18 months.",
       src:["CRS R46925 (Jul 11 2024)","Air & Space Forces Magazine"]},

      {name:"Mjölnir", start:2021, match:["mjolnir","mjölnir"], code:"THOR follow-on", status:"demo", power:"HPM (next-gen)",
       blurb:"The 'hammer' that follows THOR — a deployable, mass-producible high-power microwave prototype.",
       cost:["$26M contract (Feb 2022)."],
       timeline:[{d:"Jul 2021",e:"AFRL solicits THOR follow-on"},
                 {d:"Feb 2022",e:"Leidos awarded $26M"},
                 {d:"Early 2024",e:"Prototype delivery"}],
       suppliers:"Leidos.",
       news:[{d:"2024",t:"Improves range, reliability and manufacturing readiness over THOR for production at scale."}],
       note:"Matches the original chart.",
       src:["CRS R46925 (Jul 11 2024)"]},

      {name:"Phaser", start:2019, match:["phaser"], code:"Raytheon HPM", status:"demo", power:"HPM (short-range C-UAS)",
       blurb:"A field-tested short-range microwave counter-UAS prototype.",
       cost:["$16.3M."],
       timeline:[{d:"2019–20",e:"Prototype delivered; field-tested for C-UAS"}],
       suppliers:"Raytheon (RTX).",
       news:[{d:"—",t:"Short-range area-defense microwave; informed later C-UAS HPM efforts."}],
       note:"Matches the original chart.",
       src:["CRS R46925 (Jul 11 2024)"]},

      {name:"CHIMERA", start:2024, match:["chimera","defend"], code:"Raytheon HPM", status:"demo", power:"HPM (longer-range C-UAS)",
       blurb:"A longer-range microwave counter-UAS system tested at White Sands — now folded into the joint DEFEND program.",
       cost:["Not separately disclosed.","Joint DEFEND award to RTX ~$31.3M (NSWC Dahlgren) to build two HPM prototypes for the Navy &amp; Air Force."],
       timeline:[{d:"Jan 2024",e:"Three-week field test at White Sands Missile Range"},
                 {d:"2025–26",e:"Rolled into the joint DEFEND HPM program (RTX)"}],
       suppliers:"Raytheon (RTX).",
       news:[{d:"2026",t:"CHIMERA-class HPM continues under the joint DEFEND effort to deliver Navy/AF microwave prototypes."},
             {d:"2024",t:"Extends HPM C-UAS reach beyond Phaser-class short range."}],
       note:"Matches the original chart; updated with the joint DEFEND program and the RTX HPM award.",
       src:["RTX (Jan 29 2024) — CHIMERA","CRS R46925 (Jul 11 2024)"]},

      {name:"HELWS", start:2019, match:["helws"], code:"H4 High Energy Laser Weapon System", status:"cancelled", power:"~10 kW-class HEL, ~3 km",
       blurb:"Raytheon's vehicle-mounted counter-UAS laser — fielded overseas for assessment, then closed out after the AF dropped C-UAS laser prototyping.",
       cost:["$15.5M upgrade (2021). The AF held at least three HELWS plus a palletized fourth ('H4', 2022)."],
       timeline:[{d:"Oct 2019",e:"AF takes delivery of the first HELWS (10 kW on a Polaris MRZR)"},
                 {d:"Apr 2020",e:"Deployed overseas for field tests; $15.5M upgrade contract follows (2021)"},
                 {d:"2022",e:"Raytheon delivers a palletized fourth unit ('H4')"},
                 {d:"2024–25",e:"AF determines 'no further requirements' for C-UAS prototyping; transfers HELWS to Army RCCTO, which closes it out"}],
       suppliers:"Raytheon (RTX); platform: Polaris MRZR.",
       news:[{d:"2025",t:"Closed out after the AF redirected funds to higher-priority DE transition efforts (per Laser Wars / AF FY26 budget)."}],
       note:"<b>Correction:</b> status active → <b>cancelled</b>. The AF ended HELWS C-UAS prototyping (2024) and handed the systems to the Army's RCCTO to close out (Laser Wars).",
       src:["Laser Wars (Mar 28 2026)","CRS R46925 (Jul 11 2024)"]},

      {name:"SHiELD", start:2019, match:["shield laser","lance"], code:"+ LANCE subsystem", status:"concluded", power:"Airborne HEL (pod)",
       blurb:"An ambitious fighter-pod laser to burn down incoming missiles — concluded in 2024 without ever flying on a jet.",
       cost:["RDT&amp;E demonstrator; concluded 2024."],
       timeline:[{d:"2019–23",e:"Develops LANCE laser subsystem + pod/beam-control"},
                 {d:"2024",e:"Program concluded; never flew on an aircraft"}],
       suppliers:"AFRL with Boeing (pod/integration), Lockheed Martin (beam control), Northrop Grumman (LANCE laser).",
       news:[{d:"2024",t:"Demonstrated subsystems on the ground but ended before a flight test."}],
       note:"Matches the original chart.",
       src:["CRS R46925 (Jul 11 2024)"]},

      {name:"HiJENKS / CHAMP", start:2012, match:["hijenks","champ"], code:"Counter-electronics HPM missile", status:"concept", power:"Pulsed-power HPM",
       blurb:"A joint Navy/Air Force counter-electronics cruise missile lineage — HiJENKS succeeds CHAMP.",
       cost:["RDT&amp;E; joint program."],
       timeline:[{d:"2012–15",e:"CHAMP demonstrates microwave counter-electronics from a cruise missile"},
                 {d:"~2022–23",e:"HiJENKS (High-Powered Joint Electromagnetic Non-Kinetic Strike) tested"}],
       suppliers:"AFRL / U.S. Navy joint; pulsed-power HPM payload.",
       news:[{d:"—",t:"Counter-electronics (fry electronics, not structures) rather than counter-UAS."}],
       note:"Matches the original chart.",
       src:["CRS R46925 (Jul 11 2024)"]},

      {name:"Airborne-laser graveyard", start:2010, match:["yal-1","airborne laser"], code:"YAL-1 ABL · AC-130J SHiELD", status:"concluded", power:"Megawatt-class (chemical, historical)",
       blurb:"The cautionary history: the megawatt chemical Airborne Laser and the shelved gunship laser.",
       cost:["YAL-1: ~$5.3B over its life."],
       timeline:[{d:"Feb 2010",e:"YAL-1 (747-mounted chemical oxygen-iodine laser) shoots down a boost-phase missile"},
                 {d:"2011",e:"YAL-1 cancelled"},
                 {d:"2020s",e:"AC-130J gunship laser (SHiELD-adjacent) shelved"}],
       suppliers:"Boeing (YAL-1 aircraft), Northrop Grumman / Lockheed (laser).",
       news:[{d:"—",t:"Stands as the benchmark for why solid-state, electric lasers replaced chemical ones."}],
       note:"Historical context, unchanged from the original chart.",
       src:["CRS R46925 (Jul 11 2024)"]},

      {name:"Air-to-air laser drone (MQ-9B)", start:2025, match:["mq-9b","general atomics laser","laser drone","air-to-air laser"], code:"General Atomics airborne HEL pod", status:"demo", power:"25 kW-class (scalable toward 300 kW)",
       blurb:"A drone-mounted laser pod for air-to-air drone (and eventual missile) defeat — the airborne DE concept MDA wants as a 'fleet of laser drones' for Golden Dome.",
       cost:["Company-funded development; not separately disclosed."],
       timeline:[{d:"Apr 2025",e:"General Atomics confirms a drone-killing air-to-air laser in development (shown at Sea-Air-Space)"},
                 {d:"2025–26",e:"Ground testing; not yet flown"},
                 {d:"Apr 2026",e:"MDA signals interest in a fleet of missile-killing laser drones"}],
       suppliers:"General Atomics Aeronautical Systems (GA-ASI); platform: MQ-9B-class UAS.",
       news:[{d:"2026",t:"Revives the airborne-laser idea on an unmanned platform after SHiELD's ground-only conclusion."}],
       note:"Airborne (not space) DE; tied to MDA's boost-phase / Golden Dome non-kinetic ambitions.",
       src:["Naval News (Apr 2025)","Defense News (Apr 24 2026)"]}
    ],

    space:[
      {name:"Space-Based Laser (SBL) / Zenith Star", start:1984, match:["space based laser","space-based laser","sbl","zenith star","alpha laser"], code:"SDI-era orbital boost-phase laser", status:"shelved", power:"Megawatt-class (chemical, historical)",
       blurb:"The 'Star Wars' dream: a constellation of orbiting megawatt chemical lasers to kill missiles in boost phase — ground-tested, never orbited.",
       cost:["SDI / BMDO S&amp;T; the Space-Based Laser Integrated Flight Experiment was cancelled in FY2002."],
       timeline:[{d:"1980s",e:"SDIO funds Zenith Star / the Alpha hydrogen-fluoride laser"},
                 {d:"1991",e:"Alpha laser reaches megawatt class in ground tests"},
                 {d:"FY2002",e:"Space-Based Laser Integrated Flight Experiment cancelled"}],
       suppliers:"TRW, Lockheed Martin, Boeing (SDI-era team).",
       news:[{d:"2025–26",t:"Cited as the cautionary precedent as 'Star Wars'-style space-DE concepts resurface under Golden Dome."}],
       note:"Historical foundation. <b>No U.S. space-based laser weapon has ever been orbited.</b>",
       src:["GlobalSecurity — SBL","CRS R46925 (Jul 11 2024)"]},

      {name:"Space / orbital HPM S&T", start:2019, match:["high power microwave satellite","space hpm","orbital microwave","warden"], code:"DARPA / AFRL RF-DE science & technology", status:"concept", power:"High-power microwave (RF DE), concept",
       blurb:"Science-and-technology work on high-power microwave / RF directed energy with potential space or counter-space application — no fielded orbital HPM weapon exists.",
       cost:["S&amp;T funding (e.g., DARPA WARDEN-class RF-DE programs)."],
       timeline:[{d:"2019+",e:"AFRL / DARPA RF-DE counter-electronics S&amp;T matures"},
                 {d:"2025–26",e:"Renewed interest in space-relevant DE under Golden Dome"}],
       suppliers:"DARPA, AFRL with industry (Raytheon, Epirus, BAE).",
       news:[{d:"2026",t:"Remains research; no verified space-based HPM weapon — space application is aspirational."}],
       note:"⚠ Concept / S&amp;T only. Laser communications (e.g., SDA optical crosslinks) are NOT weapons and are excluded.",
       src:["CRS R46925 (Jul 11 2024)","Laser Wars (Jun 4 2026)"]},

      {name:"Space Force counterspace DE", start:2021, match:["space force laser","orbital directed energy","space superiority","counterspace","satellite dazzle"], code:"Directed energy for space superiority", status:"concept", power:"Ground &amp; orbital lasers (dazzle/damage)",
       blurb:"The Space Force's stated intent to use directed energy — one of its three counterspace weapon classes (DE, RF, kinetic) — to dazzle or damage satellites and sensors.",
       cost:["Not disclosed (largely classified)."],
       timeline:[{d:"Jun 2021",e:"Space Systems Command names DE for space superiority"},
                 {d:"Mar 2025",e:"CSO Gen. Saltzman publicly cites DE lasers (ground + orbiting) among needed weapons"}],
       suppliers:"TBD / classified.",
       news:[{d:"2025",t:"'It's official: the Space Force wants laser weapons' — public acknowledgement of orbital DE ambitions."}],
       note:"Doctrine / concept, much of it classified. Distinct from RF jammers like the Counter Communications System / 'Meadowlands,' which are electronic warfare — <b>not</b> directed energy.",
       src:["C4ISRNET (Jun 16 2021)","Task & Purpose (Mar 2025)"]},

      {name:"Golden Dome DE layer (MDA)", start:2024, match:["mda directed energy","boost phase laser","non-kinetic","golden dome directed energy","directed energy missile defense"], code:"Directed-energy missile-defense layer", status:"concept", power:"HEL / HPM (boost-phase, concept)",
       blurb:"The directed-energy slice of Golden Dome: an effort to mature lasers / HPM as a non-kinetic boost-phase missile-defense layer, largely from airborne (and eventually space) platforms.",
       cost:["$452M FY2027 RDT&amp;E for DE 'System Development, Integration &amp; Assessment' under Golden Dome — &gt;3× the ~$142M prior level (not space-exclusive)."],
       timeline:[{d:"2024",e:"MDA directed-energy roadmap"},
                 {d:"Apr 15 2026",e:"MDA leadership testifies it is 'all in' on directed energy"},
                 {d:"FY2027",e:"$452M Golden Dome DE request"}],
       suppliers:"TBD (General Atomics airborne HEL among concepts).",
       news:[{d:"2026",t:"MDA frames DE as a 'critical non-kinetic layer' — but officials caution space-based DE intercept remains years out."}],
       note:"⚠ The $452M Golden Dome DE line is DoD-wide, not space-specific. Most of the Golden Dome 'space layer' is <b>kinetic</b> (space-based interceptors), not directed energy — see the SBI entry.",
       src:["CRS IF11882 (Jan 2026)","Federal News Network (Apr 2026)","Defense News (Apr 28 2026)"]},

      {name:"Space-Based Interceptor (SBI)", start:2025, match:["space-based interceptor","sbi","boost phase interceptor","golden dome space layer"], code:"Golden Dome orbital interceptor (KINETIC)", status:"platform", power:"Kinetic — NOT directed energy",
       blurb:"The Golden Dome 'space layer' most often conflated with space lasers — but the Pentagon confirms it is KINETIC interceptors, not directed energy. Included here to draw the line.",
       cost:["Part of the ~$17.5B FY2027 Golden Dome request; prototype interceptors reportedly low unit cost."],
       timeline:[{d:"Nov 2025",e:"Space Force awards first space-based boost-phase interceptor prototype OTAs"},
                 {d:"Apr 24 2026",e:"~12 firms named for SBI work"},
                 {d:"~2028",e:"Targeted prototype readiness"}],
       suppliers:"Northrop Grumman, Lockheed Martin, Anduril, True Anomaly (among awardees).",
       news:[{d:"2026",t:"Golden Dome leadership signals SBIs aren't guaranteed; explicitly 'kinetic solutions rather than non-kinetic systems that use directed energy.'"}],
       note:"⚠ <b>KINETIC, not DE</b> — shown for disambiguation because it is the marquee Golden Dome space-layer effort.",
       src:["Breaking Defense (Nov 2025) — SBI","Air & Space Forces Mag (Dec 9 2025)"]}
    ]
  },

  DISCREPANCIES: [
    {tag:"t-fix", h:"E-HEL power: 30 kW, not '50–300 kW TBD'",
     was:"Original chart: E-HEL = 'Army's first DE program of record · skips heavy prototyping · 50–300 kW TBD · requirements phase.'",
     now:"FY2027 budget + RFI: E-HEL is a modular <b>30 kW counter-UAS</b> laser, already in source-selection with a production decision targeted Q4 FY2026. The 150→300 kW counter-cruise-missile role is JLWS, a separate effort."},
    {tag:"t-add", h:"AMP-HEL — entirely missing from the charts",
     was:"Not present in any of the four source charts.",
     now:"A 20 kW AeroVironment LOCUST laser on the Infantry Squad Vehicle. Fired by the SecArmy at White Sands May 27 2026; the spearhead of the domestic 'laser dome.' Added as a full Army card."},
    {tag:"t-clar", h:"P-HEL supplier: BlueHalo → AeroVironment",
     was:"Original chart: P-HEL = 'BlueHalo LOCUST.'",
     now:"AeroVironment acquired BlueHalo (merger agreement Nov 2024, closed ~mid-2025). LOCUST / P-HEL / AMP-HEL are now AeroVironment products. Supplier labels updated."},
    {tag:"t-clar", h:"JLWS — name + power enriched",
     was:"Original chart: 'Joint Laser Weapon System · counter-cruise-missile · requirements phase.'",
     now:"Confirmed JLWS, but also rendered 'Joint Laser <i>Warfighting</i> System.' Added detail: containerized <b>150 kW → ≥300 kW</b>, Joint Beam Control System for 300–500 kW, and the $675.93M FY2028–31 joint funding profile."},
    {tag:"t-fix", h:"$142M Golden Dome DE was OBBBA reconciliation money (earlier note corrected)",
     was:"A prior site note claimed the $142M was NOT from reconciliation — 'treat as unverified.'",
     now:"Per Laser Wars' FY2027 budget analysis, the <b>$142M was enacted for Golden Dome DE under the July 2025 OBBBA reconciliation act</b> (P.L. 119-21); the FY2027 <b>$452M</b> request more than triples it. OBBBA also carried ~$250M for DE R&D more broadly. Corrected throughout."},
    {tag:"t-clar", h:"Songbow is no longer 'single-source'",
     was:"Original chart: 'Songbow appears only in the 2026 DEHEL report; treat as single-source.'",
     now:"Now corroborated by multiple outlets (Naval News, optics.org, defense press). Verified: Coherent Aerospace &amp; Defense, $29.98M (Jun 10 2025), 400 kW from 4×50 kW pulsed-fiber, completion Jan 2027."},
    {tag:"t-clar", h:"HELIOS power dispute persists (60 → 120 vs 150 kW)",
     was:"Original chart flagged the 120 vs 150 kW dispute.",
     now:"Confirmed and kept: delivered as 60 kW-class; growth target cited as 120 kW (R46925 / 2026 DEHEL) or 150 kW (R44175 Jan 2026 / Lockheed). 60 kW delivered figure consistent across sources."},
    {tag:"t-clar", h:"THOR cost: ~$15M vs ~$18M",
     was:"Original chart: THOR ~$15M.",
     now:"AFRL/Wikipedia cite ~$18M built over ~18 months. Shown as a range (~$15–18M)."},
    {tag:"t-add", h:"Big picture: FY2027 ~doubles DE to >$2B",
     was:"Original chart: FY25 unclassified DE $789.7M; 'FY26 topline not disclosed.'",
     now:"FY2027 request exceeds <b>$2B</b> in DE RDT&E, incl. $452M for Golden Dome and a multi-billion counter-drone surge (JIATF-401 five-base pilot, border, World Cup 2026, critical infrastructure)."},
    {tag:"t-fix", h:"Navy LWSD is not retired — it was reactivated",
     was:"Prior data: SSL-TM → LWSD 'closed out / retired ~2024.'",
     now:"Defense News (Mar 31 2026): after a ~$50M FY2023 deinstall, the 150 kW LWSD was restored from early 2025 and <b>shot down four drones in exercise 'Crimson Dragon' (Sept 2025).</b> Status changed retired → demo."},
    {tag:"t-clar", h:"FY2027 DE: ≈$950M (DE-specific) vs >$2B (broad)",
     was:"Single headline figure of '>$2B' for DoD DE.",
     now:"The official headline is <b>&gt;$2B</b>; a Laser Wars estimate sums the named DE program elements to <b>≈$950M</b> (vs ≈$442M in FY26). Both are right at different scopes — '>$2B' folds in DE-inclusive counter-UAS / IFPC / M-SHORAD lines."},
    {tag:"t-add", h:"New: dedicated Space tab + space-DE disambiguation",
     was:"No coverage of space-based directed energy.",
     now:"Added a <b>Space</b> tab. Key clarification: most of the Golden Dome 'space layer' is <b>kinetic</b> (space-based interceptors), and RF jammers like 'Meadowlands' are electronic warfare — <b>not</b> DE. True space-based DE remains concept / S&amp;T; no U.S. space-based laser/HPM weapon has been orbited."},
    {tag:"t-add", h:"New entries: carrier LOCUST, Project METEOR, GA laser drone, FY2027 Budget page",
     was:"Not previously tracked.",
     now:"Added the carrier-fired <b>LOCUST</b> (first laser fired from a U.S. supercarrier, CVN-77, Oct 2025), Navy <b>Project METEOR</b> shipboard HPM (flagged single-source), the General Atomics <b>MQ-9B air-to-air laser drone</b>, and a dedicated <b>FY2027 Budget</b> page with official document links. JLWS tied to the DoD push for a battle-ready laser demo by <b>summer 2028</b>."},
    {tag:"t-fix", h:"HELWS is cancelled, not active",
     was:"Site listed HELWS as an active Air Force C-UAS laser.",
     now:"Per Laser Wars [Status, Mar 2026], the AF ended HELWS C-UAS prototyping in 2024 and transferred it to the Army's RCCTO, which closed it out. Status changed active → cancelled."},
    {tag:"t-fix", h:"DE M-SHORAD fully cancelled &amp; demilitarized",
     was:"Site said 'shelved.'",
     now:"DOT&E (Mar 2026) &amp; Laser Wars: the Army is 'no longer pursuing DE M-SHORAD as a program of record'; all four prototypes were <b>demilitarized</b> after a June 2025 Fort Sill live-fire (one to the ADA Training Facility). Status → cancelled; delivery re-dated to late 2023."},
    {tag:"t-clar", h:"ODIN is built by VTG Defense (not 'government-built')",
     was:"Site credited ODIN to 'U.S. Navy / NSWC Dahlgren (government-built).'",
     now:"Laser Wars [Status]: ODIN is Navy-designed but produced by contractor <b>VTG Defense</b>; &gt;$200M spent; the FY27 procurement line is zeroed. Supplier updated; USS Spruance &amp; Stockdale confirmed (USS Dewey dropped)."},
    {tag:"t-add", h:"New: U.S. Marine Corps tab (HELEX, MADIS, CLaWS)",
     was:"No Marine Corps coverage.",
     now:"Added a <b>Marine Corps</b> tab from Laser Wars [Status]: the ONR 10 kW <b>HELEX</b>, a <b>LOCUST-on-JLTV</b> effort for a future MADIS increment, and the cancelled Boeing <b>CLaWS</b>."},
    {tag:"t-clar", h:"HELIOS: $225.4M obligated; reached ~1/3 power in 2025",
     was:"Site cited '~$150M (2018); ~$350M to date.'",
     now:"Per Laser Wars: <b>$225.4M obligated</b> (2018 Lockheed contract ceiling $1.1B, options unexercised). The acting CNO said HELIOS hit only ~1/3 power in 2025 testing (Lockheed disputes); the CEO later cited a four-drone at-sea kill (Jan 2026)."},
    {tag:"t-add", h:"First confirmed US laser kill: AMP-HEL (friendly fire)",
     was:"Not previously noted.",
     now:"Laser Wars [Status]: the first publicly confirmed US laser weapon kill was an AMP-HEL at the border (Feb 2026) — a <b>friendly-fire</b> downing of a CBP drone after CBP used the system without FAA coordination (the El Paso airspace shutdown)."}
  ]
};
