/* =====================================================================
   DIRECTED ENERGY TRACKER — DATA FILE
   ---------------------------------------------------------------------
   This is the ONLY file that changes during a daily/periodic update.
   The layout (index.html) stays fixed. To update:
     • bump META.lastUpdated (YYYY-MM-DD) and META.dataVersion
     • append items to a program's `news:[]` array (newest first)
     • adjust a `status`, `power`, `cost`, `timeline`, or `suppliers` field
     • add a row to DISCREPANCIES if new reporting contradicts old data
   Do NOT edit index.html for content changes.
   ===================================================================== */
window.DE_DATA = {

  META: {
    title: "U.S. Directed Energy Weapon Programs — Live Tracker",
    fyFocus: "FY2027",
    lastUpdated: "2026-06-01",   // <-- bump on every data edit
    dataVersion: 2,
    // Live-news feed (GDELT DOC 2.0 — no API key). Raw query; encoded at runtime.
    newsQuery: '("directed energy" OR "high energy laser" OR "high-power microwave" OR "laser weapon") (military OR Pentagon OR Navy OR Army OR "Air Force" OR drone OR "Golden Dome")',
    newsTimespan: "3m"           // GDELT timespan window (e.g. 1m, 3m, 6m)
  },

  STATUS: {
    active:    {l:"Active",            c:"var(--active)"},
    new:       {l:"New / Successor",   c:"var(--new)"},
    shelved:   {l:"Shelved",           c:"var(--shelved)"},
    concept:   {l:"Lineage / Concept", c:"var(--concept)"},
    fielded:   {l:"Fielded",           c:"var(--fielded)"},
    counter:   {l:"Counter-ASCM",      c:"var(--counter)"},
    demo:      {l:"Demo",              c:"var(--demo)"},
    platform:  {l:"Platform",          c:"var(--platform)"},
    retired:   {l:"Retired",           c:"var(--concept)"},
    concluded: {l:"Concluded",         c:"var(--shelved)"}
  },

  SOURCES: [
    {s:"CRS R46925 (Jul 11 2024)", t:"DoD Directed Energy Weapons: Background & Issues for Congress", u:"https://www.congress.gov/crs-product/R46925"},
    {s:"CRS R44175", t:"Navy Shipboard Lasers: Background & Issues for Congress", u:"https://www.congress.gov/crs-product/R44175"},
    {s:"CRS IF11882 (Jan 2026)", t:"Defense Primer: Directed-Energy Weapons", u:"https://www.congress.gov/crs-product/IF11882"},
    {s:"CRS IF12421 (Jan 2026)", t:"The Army's Indirect Fire Protection Capability (IFPC) System", u:"https://www.congress.gov/crs-product/IF12421"},
    {s:"DoD/War Comptroller", t:"FY2027 Budget Request Overview Book", u:"https://comptroller.war.gov/Portals/45/Documents/defbudget/FY2027/FY2027_Budget_Request_Overview_Book.pdf"},
    {s:"Laser Wars (Apr 8 2026)", t:"The Pentagon's FY2027 Budget Bet on Directed Energy", u:"https://www.laserwars.net/p/defense-department-fy2027-budget-request-directed-energy-laser-weapon-funding"},
    {s:"The Defense News", t:"Pentagon Requests Over $2B for Directed Energy in FY2027", u:"https://www.thedefensenews.com/news-details/Pentagon-Requests-Over-2-Billion-for-Directed-Energy-Research-in-FY2027-Budget/"},
    {s:"Defense News (Apr 28 2026)", t:"What we know about the military's new joint laser weapon system", u:"https://www.defensenews.com/newsletters/daily-news-roundup/2026/04/28/what-we-know-about-the-us-militarys-new-joint-laser-weapon-system/"},
    {s:"Military Times (Mar 23 2026)", t:"The US Army is already ditching its most powerful laser weapon yet", u:"https://www.militarytimes.com/industry/techwatch/2026/03/23/the-us-army-is-already-ditching-its-most-powerful-laser-weapon-yet/"},
    {s:"Military Times (Apr 13 2026)", t:"US military eyes high-energy 'laser dome' for domestic air defense", u:"https://www.militarytimes.com/industry/techwatch/2026/04/13/us-military-eyes-high-energy-laser-dome-for-domestic-air-defense/"},
    {s:"DefenseScoop (Nov 3 2025)", t:"Army takes another step toward E-HEL drone-killing lasers", u:"https://defensescoop.com/2025/11/03/army-enduring-high-energy-laser-ehel-rfi-counter-uas/"},
    {s:"Breaking Defense (Nov 2025)", t:"Give 'em E-HEL: Army seeks industry ideas for C-UAS lasers", u:"https://breakingdefense.com/2025/11/give-em-e-hel-army-seeks-industry-ideas-for-counter-drone-laser-systems/"},
    {s:"DefenseScoop (Feb 18 2026)", t:"Navy brass sees future battleship as catalyst to scale lasers", u:"https://defensescoop.com/2026/02/18/navy-lasers-admiral-caudle-golden-fleet-battleship/"},
    {s:"DefenseScoop (Mar 16 2026)", t:"Inside a 'first of its kind' counter-drone laser test", u:"https://defensescoop.com/2026/03/16/inside-counter-drone-laser-test-new-mexico-white-sands/"},
    {s:"Epirus (Jul 17 2025)", t:"Epirus receives $43.5M for IFPC-HPM Gen II", u:"https://www.epirusinc.com/press-releases/epirus-receives-43-million-contract-from-u-s-army-for-ifpc-hpm-generation-ii-systems"},
    {s:"AeroVironment / BlueHalo", t:"AeroVironment to acquire BlueHalo", u:"https://bluehalo.com/aerovironment-to-acquire-bluehalo/"},
    {s:"AeroVironment", t:"AV delivers first two AMP-HEL (LOCUST) systems to US Army", u:"https://investor.avinc.com/news-releases/news-release-details/av-delivers-first-two-multi-purpose-high-energy-laser-systems-us"},
    {s:"The War Zone (TWZ)", t:"USS Preble used HELIOS to zap four drones", u:"https://www.twz.com/sea/uss-preble-used-helios-laser-to-zap-four-drones-in-expanding-testing"},
    {s:"optics.org / Naval News", t:"Coherent wins ~$30M for 400 kW Songbow laser; HELCAP 300 kW", u:"https://optics.org/news/16/6/21"},
    {s:"Task & Purpose", t:"Pentagon names five bases for anti-drone energy weapons", u:"https://taskandpurpose.com/news/laser-drones-pentagon-base-defense/"},
    {s:"GovConWire / ExecutiveGov", t:"Army FY2027 C-sUAS budget ($994.1M SHORAD line)", u:"https://www.govconwire.com/articles/csuas-army-fy2027-budget-cuas-raytheon-aerovironment"},
    {s:"CSIS", t:"Unpacking the $1.5T FY2027 Defense Budget Topline", u:"https://www.csis.org/analysis/unpacking-15-trillion-fy-2027-defense-budget-topline"}
  ],

  /* Headline funding cards on the Overview tab */
  FUNDING: [
    {lab:"Total DoD DE RDT&E", big:"&gt;$2.0B", delta:'FY2027 request · <span class="up">▲</span> ~2× the ~$1B/yr of the last 5 years',
     ctx:"FY25 unclassified DE req was $789.7M (down from $1.1B appropriated in FY24)."},
    {lab:"Golden Dome DE", big:"$452M", delta:'FY2027 RDT&E · <span class="up">▲</span> &gt;3× the $142M enacted',
     ctx:"For development, integration & assessment of DE for Golden Dome. The $142M was enacted via the July 2025 reconciliation act (P.L. 119-21 / OBBBA)."},
    {lab:"Army — SHORAD/C-UAS DE line", big:"$994.1M", delta:'FY2027 · <span class="up">▲</span> from $693.4M',
     ctx:"Bundled line covering DE (E-HEL, AMP-HEL), handheld, and kinetic/non-kinetic interceptors — not pure laser $$."},
    {lab:"Navy DE & electric weapons", big:"$94M", delta:'FY2027 RDT&E · <span class="up">▲</span> from $14.5M (FY26 req)',
     ctx:"Funds HELIOS sustainment, HELCAP upgrades, JBCS and containerized JLWS. FY25 broad Navy DE was $82.4M."},
    {lab:"Reconciliation top-up", big:"+$250M", delta:"P.L. 119-21 (OBBBA, Jul 2025)",
     ctx:"Via USD(R&E) for DE development/testing; $142M of that flowed to Golden Dome DE."},
    {lab:"Counter-drone surge (FY2027)", big:"~$2B+", delta:"across R&D + procurement",
     ctx:"Incl. $580M JIATF-401 R&D, ~$800M potential procurement, $158M critical-infrastructure, $100M World Cup 2026, $20M border. Context: $1.5T FY27 defense topline (CSIS)."}
  ],

  DATA: {
    army:[
      {name:"E-HEL", code:"Enduring High Energy Laser", status:"new", power:"30 kW (modular)",
       blurb:"Army's first planned DE program of record — a modular counter-UAS laser replacing DE M-SHORAD.",
       cost:["Funded inside the Army's SHORAD/C-UAS line (part of the $994.1M FY2027 request).",
             "Navy adds $4.82M for marinization (development/integration).",
             "Plan: procure 2 in FY2026, 2 in FY2027; produce &amp; rapidly field up to 24 systems over ~5 years."],
       timeline:[{d:"Oct 30 2025",e:"RFI issued to inform a production effort"},
                 {d:"Q2 FY2026",e:"Competitive source selection; first prototype expected"},
                 {d:"Q4 FY2026",e:"Production decision targeted (would make it the Army's first DE PoR)"},
                 {d:"End FY2027",e:"First initial-procurement units delivered"}],
       suppliers:"TBD via open competition — incumbents include AeroVironment (LOCUST) and other DE primes.",
       news:[{d:"2026",t:"Geared specifically at small UAS / one-way-attack drones; succeeds the shelved 50 kW DE M-SHORAD."},
             {d:"2025",t:"Army framed E-HEL as a deliberately 'enduring,' modular design to avoid the obsolescence that dogged earlier prototypes."}],
       note:"<b>Correction vs original chart:</b> E-HEL is a <b>30 kW counter-drone</b> laser, <u>not</u> '50–300 kW TBD.' The higher-power (150→300 kW) counter-cruise-missile role belongs to JLWS. E-HEL is also further along than 'requirements phase' — it is at source-selection / production-decision, and it predates the March 2026 CRS report (RFI was Oct 2025).",
       src:["DefenseScoop (Nov 3 2025)","Breaking Defense (Nov 2025)","Defense News (Apr 28 2026)"]},

      {name:"AMP-HEL", code:"Army Multi-Purpose High Energy Laser", status:"active", power:"20 kW (LOCUST)",
       blurb:"NOT in the original chart. Vehicle-mounted 20 kW LOCUST laser — the spearhead of the domestic 'laser dome.'",
       cost:["~$3 per engagement (vs millions per missile interceptor).",
             "Initial Army requirement: 24 systems; LOCUST X3 architecture scaled for ISV and JLTV fleets."],
       timeline:[{d:"2025–26",e:"AeroVironment delivers first two AMP-HEL prototypes"},
                 {d:"Feb 2026",e:"Deployments near Fort Bliss & Fort Hancock trigger temporary El Paso airspace closures"},
                 {d:"Mar 2026",e:"FAA safety test at White Sands (Boeing 767 fuselage, 8 sec, no damage) — clears the 'laser dome'"},
                 {d:"May 27 2026",e:"Sec. of the Army Dan Driscoll personally fires AMP-HEL on an Infantry Squad Vehicle, downing a drone"}],
       suppliers:"AeroVironment (AV) — formerly BlueHalo — LOCUST Laser Weapon System; platform: GM Defense Infantry Squad Vehicle (ISV).",
       news:[{d:"May 2026",t:"SecArmy demo at White Sands showcased it as the centerpiece of accelerated counter-drone fielding."},
             {d:"Apr 2026",t:"Named among systems for the JIATF-401 five-base directed-energy C-UAS pilot."}],
       note:"<b>New program</b> absent from the source charts. Closely related to P-HEL (same 20 kW LOCUST family) but vehicle-mounted on the ISV rather than palletized.",
       src:["AeroVironment","Military Times (Apr 13 2026)","DefenseScoop (Mar 16 2026)"]},

      {name:"JLWS", code:"Joint Laser Weapon System", status:"new", power:"150 kW → ≥300 kW (JBCS: 300–500 kW)",
       blurb:"Joint Army–Navy successor to IFPC-HEL — a containerized counter-cruise-missile laser inside Golden Dome.",
       cost:["Combined Army+Navy vision: <b>$675.93M</b> R&amp;D through FY2031.",
             "Army: $337.8M (FY2028–FY2031). Navy: +$243.3M R&amp;D.",
             "Navy near-term: $31.7M for Joint Beam Control System (JBCS) as soon as Q4 FY2026; $30M to procure/test containerized JLWS by Mar 2027."],
       timeline:[{d:"2026",e:"Army closes out IFPC-HEL activities first; requirements phase"},
                 {d:"Q4 FY2026",e:"Navy plans first JBCS development contracts"},
                 {d:"Mar 2027",e:"Containerized JLWS procurement/testing contracts"},
                 {d:"FY2028+",e:"Army funding ramps; scale toward ≥300 kW"}],
       suppliers:"Lockheed Martin is the likely prime (technical lead on both HELIOS and IFPC-HEL; already building a containerized HELIOS). Army budget line: Expanded Mission Area Missile (EMAM).",
       news:[{d:"Apr 2026",t:"Defense News laid out the joint funding profile; the system starts at a containerized 150 kW with a path to 300 kW+."},
             {d:"Mar 2026",t:"Confirmed as the destination for IFPC-HEL's divested prototype and lessons learned."}],
       note:"<b>Name clarification:</b> rendered both 'Joint Laser <i>Weapon</i> System' (Defense News, original chart) and 'Joint Laser <i>Warfighting</i> System' (Military Times) — same JLWS acronym. Power detail (150→300 kW + JBCS) is an enrichment over the original 'counter-cruise-missile' note.",
       src:["Defense News (Apr 28 2026)","Military Times (Mar 23 2026)"]},

      {name:"IFPC-HEL", code:"\"Valkyrie\"", status:"shelved", power:"300 kW",
       blurb:"The most powerful U.S. laser built to date — shelved in 2026 rather than transitioned to a program of record.",
       cost:["$220.8M Other Transaction Authority agreement (Jul 2023) for four prototypes.",
             "Reduced from four prototypes to a single prototype as funding was cut."],
       timeline:[{d:"Sep 2022",e:"300 kW demonstrator delivered (HEL-TVD lineage)"},
                 {d:"Jul 2023",e:"$220.8M OTA for 4 prototypes (Dynetics/Lockheed)"},
                 {d:"Jan 2026",e:"Army still publicly planned a program-of-record transition in FY2025"},
                 {d:"Mar 9 2026",e:"CRS report reveals the Army has dropped the PoR transition"},
                 {d:"Summer 2026",e:"Developmental testing at Dugway Proving Ground, UT"},
                 {d:"~Sep 2026",e:"Final prototype delivered, then 'divested as a fielding candidate' to inform JLWS"}],
       suppliers:"Dynetics (a Leidos company) prime / system integrator; Lockheed Martin 300 kW laser; truck-and-trailer mounted.",
       news:[{d:"Mar 2026",t:"\"Results from the lab and test ranges were very different from the tactical environment\" — the recurring theme behind the shelving."},
             {d:"2026",t:"Prototype undergoing final lab testing at Lockheed's New Jersey facility before Dugway."}],
       note:"Consistent with the original chart (SHELVED). Added detail: Sept 2022 demonstrator, Dugway summer 2026, Sept 2026 delivery, explicit 'divest to JLWS.' CRS source date is <b>March 9, 2026</b>.",
       src:["Military Times (Mar 23 2026)","CRS IF12421 (Jan 2026)","Defense News (Apr 28 2026)"]},

      {name:"DE M-SHORAD", code:"\"Guardian\"", status:"shelved", power:"50 kW",
       blurb:"Stryker-mounted 50 kW laser; first fielded DE maneuver-SHORAD — shelved after disappointing soldier feedback.",
       cost:["Took a ~$38M cut in FY25 and a ~$186M out-year cut.",
             "A platoon's worth (4 systems) was built and sent to CENTCOM."],
       timeline:[{d:"2021–22",e:"Prototypes delivered; first platoon equipped"},
                 {d:"2024",e:"4 systems sent to CENTCOM; hands-on soldier assessments in the Middle East"},
                 {d:"FY2025–26",e:"Shelved; folded into E-HEL"}],
       suppliers:"RTX (Raytheon) laser; Kord Technologies integrator; platform: Stryker A1.",
       news:[{d:"2024",t:"Army acquisition chief Doug Bush: initial feedback \"not overwhelmingly positive\"; lab/range results differed from the tactical environment (thermal, dust, mobility, maintainability)."},
             {d:"2026",t:"Officially superseded by the Enduring HEL (E-HEL)."}],
       note:"Consistent with the original chart (SHELVED). Funding-cut figures and the soldier-feedback rationale verified.",
       src:["Military Times (Mar 23 2026)","CRS R46925 (Jul 11 2024)"]},

      {name:"IFPC-HPM", code:"\"Leonidas\"", status:"active", power:"HPM (GaN AESA microwave)",
       blurb:"Epirus high-power microwave for swarm defeat — the Army DE effort closest to a program of record.",
       cost:["First four IFPC-HPM systems: ~$66M.",
             "Gen II contract: $43.55M (Jul 17 2025, RCCTO) for two Gen II systems + tests/spares."],
       timeline:[{d:"2023–24",e:"Four Gen I systems delivered; new-equipment training & developmental testing complete"},
                 {d:"Jul 2025",e:"$43.55M Gen II award (2 systems)"},
                 {d:"Aug–Sep 2025",e:"Gen II system deliveries"},
                 {d:"Oct 2025",e:"Test & evaluation at NAWS China Lake, CA"}],
       suppliers:"Epirus, Inc. (Leonidas, GaN-based solid-state AESA microwave).",
       news:[{d:"2025",t:"Gen II promises >2× effective range, ~+30% power, high-density batteries, long-pulse / high-duty burst modes."},
             {d:"2025",t:"Informing a potential program of record under the Army Transformation Initiative."}],
       note:"Matches the original chart ($66M + $43.55M Gen II). Verified contract value $43,551,060.",
       src:["Epirus (Jul 17 2025)","CRS R46925 (Jul 11 2024)"]},

      {name:"P-HEL", code:"Palletized High Energy Laser", status:"active", power:"20 kW (LOCUST)",
       blurb:"The Army's surprise operational win — a palletized 20 kW LOCUST laser quietly deployed overseas.",
       cost:["Low-cost, rapidly fielded; exact value not broken out publicly. ~$3/shot economics like AMP-HEL."],
       timeline:[{d:"~2022–23",e:"Deployed overseas for base defense"},
                 {d:"2024–25",e:"Reported 'proving successful' against UAS; LOCUST also tested from aircraft carriers"}],
       suppliers:"AeroVironment (AV) — formerly BlueHalo — LOCUST Laser Weapon System (palletized).",
       news:[{d:"2025",t:"BlueHalo's LOCUST became 'first to operationally field' a DE laser; AV completed its BlueHalo acquisition (~mid-2025)."},
             {d:"2026",t:"Its success underwrote momentum for AMP-HEL and E-HEL."}],
       note:"<b>Supplier update:</b> 'BlueHalo LOCUST' is now an <b>AeroVironment</b> product (AV acquired BlueHalo; merger agreement Nov 2024, closed ~H1 2025).",
       src:["AeroVironment / BlueHalo","CRS R46925 (Jul 11 2024)"]},

      {name:"Power-scaling lineage", code:"HELMTT → HEL-TVD → IFPC-HEL", status:"concept", power:"10 → 100 → 300 kW",
       blurb:"The technology ladder behind the Army's high-power lasers — each rung a step up in beam power.",
       cost:["S&amp;T / demonstrator funding; not procurement programs."],
       timeline:[{d:"2010s",e:"HELMTT — 10 kW High Energy Laser Mobile Test Truck"},
                 {d:"~2019–22",e:"HEL-TVD — 100 kW High Energy Laser Tactical Vehicle Demonstrator"},
                 {d:"2022+",e:"IFPC-HEL — 300 kW (now shelved → JLWS)"}],
       suppliers:"Various (Lockheed Martin / Dynetics on the higher rungs).",
       news:[{d:"—",t:"Also feeds the concept of lasers on next-generation combat vehicles (360°/active protection; fielding target ~2035; key decisions ~2025)."}],
       note:"Lineage/concept, unchanged from the original chart.",
       src:["CRS R46925 (Jul 11 2024)"]}
    ],

    navy:[
      {name:"HELIOS", code:"SNLWS Inc. 1", status:"fielded", power:"60 kW-class (designed to grow to 120–150 kW)",
       blurb:"The Navy's flagship shipboard HEL — Aegis-integrated on USS Preble, now downing drones in real tests.",
       cost:["~$150M development award (2018).",
             "FY2027 Navy DE line ($94M) funds additional tests &amp; maintenance / sustainment through ~FY29."],
       timeline:[{d:"2018",e:"Lockheed Martin awarded ~$150M"},
                 {d:"2022",e:"Integrated aboard USS Preble (DDG-88), Aegis-tied"},
                 {d:"2024",e:"First public photo of HELIOS firing"},
                 {d:"2025",e:"USS Preble downs four drones in expanded testing"},
                 {d:"~FY29",e:"Continued test / sustainment"}],
       suppliers:"Lockheed Martin (spectrally-combined fiber laser, integrated optical dazzler + ISR).",
       news:[{d:"Mar 2026",t:"Press framed HELIOS as destroying cheap Iranian-style drones 'for cents' a shot."},
             {d:"2026",t:"A containerized HELIOS variant is being pushed by Congress and feeds the JLWS design."}],
       note:"<b>Power dispute (kept):</b> delivered as a 60 kW-class system. Growth target is cited as <b>120 kW</b> (CRS R46925, 2026 DEHEL report) or <b>150 kW</b> (CRS R44175, Jan 2026; Lockheed). The 60 kW delivered figure is consistent across all sources.",
       src:["CRS R44175","The War Zone (TWZ)","Defense News (Apr 28 2026)"]},

      {name:"ODIN", code:"Optical Dazzling Interdictor, Navy", status:"fielded", power:"Low-power dazzler",
       blurb:"The only DE system to cross fully into procurement + sustainment — a counter-ISR 'dazzler' on destroyers.",
       cost:["Government-built (low unit cost); funding moved RDT&amp;E → OPN + O&amp;MN (the 'color shift' marking fielding)."],
       timeline:[{d:"2019–22",e:"Fielded on Arleigh Burke Flt IIA destroyers"},
                 {d:"2025",e:"Eight units installed across the fleet (incl. USS Dewey, USS Stockdale)"},
                 {d:"2026",e:"Deployed operationally during Operation Epic Fury"}],
       suppliers:"U.S. Navy / NSWC Dahlgren (government-built).",
       news:[{d:"2026",t:"ODIN's operational use underscores it as the template for how DE crosses into procurement money."}],
       note:"<b>Acronym resolved:</b> 'Optical Dazzling <b>Interdictor</b>, Navy' (per Navy budget language / R44175) — original chart's 'Interdictor' is correct; R46925 used 'Interceptor.'",
       src:["CRS R44175","DefenseScoop (Feb 18 2026)"]},

      {name:"HELCAP", code:"High Energy Laser Counter-ASCM Program", status:"counter", power:"300 kW+ source",
       blurb:"The Navy's high-power counter-anti-ship-cruise-missile testbed — solving beam control, not yet a weapon.",
       cost:["RDT&amp;E, non-program-of-record. FY2027 Navy DE line includes HELCAP upgrades."],
       timeline:[{d:"2024",e:"300 kW source (adapted from HELSI) readied for intercept tests"},
                 {d:"FY2025",e:"Primary demonstrations vs surrogate ASCMs at White Sands (DETAM campaign, Laser Weapon Testbed)"},
                 {d:"FY2026",e:"Program completion; no combatant integration"}],
       suppliers:"Navy (ONR / NSWC) with HELSI-derived laser source; beam-control / atmospheric-turbulence focus.",
       news:[{d:"2026",t:"Lessons hand off toward the joint JLWS rather than a standalone HELCAP weapon."}],
       note:"Matches the original chart. FY2027 'upgrade' funding noted despite a FY2026 completion date — treat as residual/transition funding.",
       src:["optics.org / Naval News","CRS R44175"]},

      {name:"Songbow", code:"Coherent A&D", status:"demo", power:"400 kW-class (4 × 50 kW pulsed-fiber)",
       blurb:"A new 400 kW pulsed-fiber laser effort aimed at swarms, cruise missiles and even hypersonic glide vehicles.",
       cost:["$29,981,651 cost-plus-fixed-fee (Jun 10 2025).",
             "20-month base period + 11- and 18-month options (may run concurrently)."],
       timeline:[{d:"Jun 10 2025",e:"Contract awarded to Coherent Aerospace & Defense (Murrieta, CA)"},
                 {d:"Jan 2027",e:"Scheduled completion (full DE subsystem: beam director + precision optics)"}],
       suppliers:"Coherent Aerospace &amp; Defense — coherently combining four-plus 50 kW pulsed-fiber modules.",
       news:[{d:"2025",t:"Aims at drone swarms, cruise missiles and hypersonic glide vehicles 'at the speed of light'; also remote sensing / target illumination."}],
       note:"<b>Update vs original chart:</b> no longer 'single-source' — Songbow is corroborated by multiple outlets (Naval News, optics.org, defense press). Figures verified ($29.98M; Jan 2027).",
       src:["optics.org / Naval News"]},

      {name:"BBG(X) battleship", code:"\"Trump-class\" guided-missile battleship", status:"platform", power:"2 lasers × 300 or 600 kW",
       blurb:"The Navy's future destination for high-power lasers — a large, power-rich combatant ('Golden Fleet').",
       cost:["Navy planning exceeds <b>$17B</b> for the first unit; first hull procured early 2030s."],
       timeline:[{d:"Dec 22 2025",e:"Trump administration announces the new battleship class"},
                 {d:"Early 2030s",e:"First BBG(X) procured"},
                 {d:"2030s",e:"Nuclear propulsion confirmed; armed with two lasers (300 or 600 kW each), hypersonics & rail guns"}],
       suppliers:"TBD (program early). Zumwalt-class destroyers floated as near-term laser power-generation testbeds.",
       news:[{d:"Feb 2026",t:"CNO Adm. Daryl Caudle &amp; VADM Brendan McLane cast the battleship as a 'forcing function' to scale lasers across the fleet; 600 kW could counter some ASCMs."}],
       note:"Matches the original chart (Dec 22 2025; early 2030s; 300/600 kW). Added: nuclear propulsion, >$17B unit cost, 'Golden Fleet' framing.",
       src:["DefenseScoop (Feb 18 2026)","CRS R44175"]},

      {name:"SSL-TM → LWSD", code:"Laser Weapon System Demonstrator", status:"retired", power:"150 kW",
       blurb:"Early high-power shipboard demonstrator that downed a UAV from an amphibious ship — now closed out.",
       cost:["RDT&amp;E demonstrator; closed out / retired ~2024."],
       timeline:[{d:"2019–20",e:"Installed on USS Portland (LPD-27); downed a UAV in 2020"},
                 {d:"~2024",e:"Closed out / retired"}],
       suppliers:"Northrop Grumman.",
       news:[{d:"2024",t:"Lessons rolled into the Navy's higher-power counter-ASCM efforts."}],
       note:"Unchanged from the original chart.",
       src:["CRS R44175"]},

      {name:"Layered Laser Defense", code:"LLD", status:"demo", power:"150 kW",
       blurb:"A Lockheed demo laser that killed a subsonic-cruise-missile analog — proof of principle, not to be fielded.",
       cost:["~$22M (demonstration)."],
       timeline:[{d:"2022",e:"Defeated a subsonic cruise-missile target analog in testing"}],
       suppliers:"Lockheed Martin.",
       news:[{d:"—",t:"Demonstration only; informed counter-cruise-missile laser requirements."}],
       note:"Unchanged from the original chart.",
       src:["CRS R44175"]},

      {name:"RHEL", code:"Ruggedized HEL", status:"retired", power:"—",
       blurb:"A ruggedized HEL effort that fed an 'alternate laser design'; completed and no longer active.",
       cost:["RDT&amp;E; completed."],
       timeline:[{d:"—",e:"Completed; fed an alternate laser design"}],
       suppliers:"Navy.",
       news:[{d:"—",t:"No longer an active line."}],
       note:"Unchanged from the original chart.",
       src:["CRS R44175"]}
    ],

    af:[
      {name:"THOR", code:"Tactical High-power Operational Responder", status:"demo", power:"HPM (counter-swarm)",
       blurb:"AFRL's air-base-defense microwave that disables drone swarms in a single pulse — built fast and cheap.",
       cost:["~$15–18M; built in roughly 18 months (AFRL/Wikipedia cite $18M; original chart ~$15M)."],
       timeline:[{d:"2019",e:"Initial testing begins"},
                 {d:"Apr 2023",e:"Defeats a simulated swarm at the Chestnut Test Site, Kirtland AFB"},
                 {d:"2024+",e:"Informs follow-on Mjölnir"}],
       suppliers:"AFRL with BAE Systems / Leidos / Verus Research. Ships in a 20-ft container, runs off a wall plug, ~3-hr setup; C-130 transportable.",
       news:[{d:"2023–24",t:"Swarm-defeat demo validated 'detect a cluster, pulse in nanoseconds, disable many drones' for base defense."}],
       note:"Minor cost discrepancy: original chart ~$15M; AFRL/Wikipedia state ~$18M over 18 months.",
       src:["CRS R46925 (Jul 11 2024)","Air & Space Forces Magazine"]},

      {name:"Mjölnir", code:"THOR follow-on", status:"demo", power:"HPM (next-gen)",
       blurb:"The 'hammer' that follows THOR — a deployable, mass-producible high-power microwave prototype.",
       cost:["$26M contract (Feb 2022)."],
       timeline:[{d:"Jul 2021",e:"AFRL solicits THOR follow-on"},
                 {d:"Feb 2022",e:"Leidos awarded $26M"},
                 {d:"Early 2024",e:"Prototype delivery"}],
       suppliers:"Leidos.",
       news:[{d:"2024",t:"Improves range, reliability and manufacturing readiness over THOR for production at scale."}],
       note:"Matches the original chart.",
       src:["CRS R46925 (Jul 11 2024)"]},

      {name:"Phaser", code:"Raytheon HPM", status:"demo", power:"HPM (short-range C-UAS)",
       blurb:"A field-tested short-range microwave counter-UAS prototype.",
       cost:["$16.3M."],
       timeline:[{d:"2019–20",e:"Prototype delivered; field-tested for C-UAS"}],
       suppliers:"Raytheon (RTX).",
       news:[{d:"—",t:"Short-range area-defense microwave; informed later C-UAS HPM efforts."}],
       note:"Matches the original chart.",
       src:["CRS R46925 (Jul 11 2024)"]},

      {name:"CHIMERA", code:"Raytheon HPM", status:"demo", power:"HPM (longer-range C-UAS)",
       blurb:"A longer-range microwave counter-UAS system tested at White Sands.",
       cost:["Not separately disclosed."],
       timeline:[{d:"2024",e:"Tested at White Sands Missile Range"}],
       suppliers:"Raytheon (RTX).",
       news:[{d:"2024",t:"Extends HPM C-UAS reach beyond Phaser-class short range."}],
       note:"Matches the original chart.",
       src:["CRS R46925 (Jul 11 2024)"]},

      {name:"HELWS", code:"H4 High Energy Laser Weapon System", status:"active", power:"~10 kW-class HEL, ~3 km",
       blurb:"A vehicle-mounted mobile counter-UAS laser deployed overseas for operational assessment.",
       cost:["$15.5M upgrade (2021)."],
       timeline:[{d:"2019–21",e:"Mounted on MRZR; ~3 km engagement range"},
                 {d:"2021",e:"$15.5M upgrade; deployed for overseas assessment"}],
       suppliers:"Raytheon (RTX); platform: Polaris MRZR.",
       news:[{d:"—",t:"One of the longest-running fielded-for-assessment Air Force counter-UAS lasers."}],
       note:"Matches the original chart.",
       src:["CRS R46925 (Jul 11 2024)"]},

      {name:"SHiELD", code:"+ LANCE subsystem", status:"concluded", power:"Airborne HEL (pod)",
       blurb:"An ambitious fighter-pod laser to burn down incoming missiles — concluded in 2024 without ever flying on a jet.",
       cost:["RDT&amp;E demonstrator; concluded 2024."],
       timeline:[{d:"2019–23",e:"Develops LANCE laser subsystem + pod/beam-control"},
                 {d:"2024",e:"Program concluded; never flew on an aircraft"}],
       suppliers:"AFRL with Boeing (pod/integration), Lockheed Martin (beam control), Northrop Grumman (LANCE laser).",
       news:[{d:"2024",t:"Demonstrated subsystems on the ground but ended before a flight test."}],
       note:"Matches the original chart.",
       src:["CRS R46925 (Jul 11 2024)"]},

      {name:"HiJENKS / CHAMP", code:"Counter-electronics HPM missile", status:"concept", power:"Pulsed-power HPM",
       blurb:"A joint Navy/Air Force counter-electronics cruise missile lineage — HiJENKS succeeds CHAMP.",
       cost:["RDT&amp;E; joint program."],
       timeline:[{d:"2012–15",e:"CHAMP demonstrates microwave counter-electronics from a cruise missile"},
                 {d:"~2022–23",e:"HiJENKS (High-Powered Joint Electromagnetic Non-Kinetic Strike) tested"}],
       suppliers:"AFRL / U.S. Navy joint; pulsed-power HPM payload.",
       news:[{d:"—",t:"Counter-electronics (fry electronics, not structures) rather than counter-UAS."}],
       note:"Matches the original chart.",
       src:["CRS R46925 (Jul 11 2024)"]},

      {name:"Airborne-laser graveyard", code:"YAL-1 ABL · AC-130J SHiELD", status:"concluded", power:"Megawatt-class (chemical, historical)",
       blurb:"The cautionary history: the megawatt chemical Airborne Laser and the shelved gunship laser.",
       cost:["YAL-1: ~$5.3B over its life."],
       timeline:[{d:"Feb 2010",e:"YAL-1 (747-mounted chemical oxygen-iodine laser) shoots down a boost-phase missile"},
                 {d:"2011",e:"YAL-1 cancelled"},
                 {d:"2020s",e:"AC-130J gunship laser (SHiELD-adjacent) shelved"}],
       suppliers:"Boeing (YAL-1 aircraft), Northrop Grumman / Lockheed (laser).",
       news:[{d:"—",t:"Stands as the benchmark for why solid-state, electric lasers replaced chemical ones."}],
       note:"Historical context, unchanged from the original chart.",
       src:["CRS R46925 (Jul 11 2024)"]}
    ]
  },

  DISCREPANCIES: [
    {tag:"t-fix", h:"E-HEL power: 30 kW, not '50–300 kW TBD'",
     was:"Original chart: E-HEL = 'Army's first DE program of record · skips heavy prototyping · 50–300 kW TBD · requirements phase.'",
     now:"FY2027 budget + RFI: E-HEL is a modular <b>30 kW counter-UAS</b> laser, already in source-selection with a production decision targeted Q4 FY2026. The 150→300 kW counter-cruise-missile role is JLWS, a separate effort."},
    {tag:"t-add", h:"AMP-HEL — entirely missing from the charts",
     was:"Not present in any of the four source charts.",
     now:"A 20 kW AeroVironment LOCUST laser on the Infantry Squad Vehicle. Fired by the SecArmy at White Sands May 27 2026; the spearhead of the domestic 'laser dome.' Added as a full Army card."},
    {tag:"t-clar", h:"P-HEL supplier: BlueHalo → AeroVironment",
     was:"Original chart: P-HEL = 'BlueHalo LOCUST.'",
     now:"AeroVironment acquired BlueHalo (merger agreement Nov 2024, closed ~mid-2025). LOCUST / P-HEL / AMP-HEL are now AeroVironment products. Supplier labels updated."},
    {tag:"t-clar", h:"JLWS — name + power enriched",
     was:"Original chart: 'Joint Laser Weapon System · counter-cruise-missile · requirements phase.'",
     now:"Confirmed JLWS, but also rendered 'Joint Laser <i>Warfighting</i> System.' Added detail: containerized <b>150 kW → ≥300 kW</b>, Joint Beam Control System for 300–500 kW, and the $675.93M FY2028–31 joint funding profile."},
    {tag:"t-clar", h:"Reconciliation DE figure: $250M vs $142M",
     was:"Original chart: 'Reconciliation Act (P.L. 119-21) added $250M for DE via USD(R&E).'",
     now:"Both are right at different scopes: the July 2025 reconciliation act added ~$250M via USD(R&E) for DE dev/testing, of which <b>$142M</b> was the Golden Dome DE slice. FY2027 then requests $452M for Golden Dome DE."},
    {tag:"t-clar", h:"Songbow is no longer 'single-source'",
     was:"Original chart: 'Songbow appears only in the 2026 DEHEL report; treat as single-source.'",
     now:"Now corroborated by multiple outlets (Naval News, optics.org, defense press). Verified: Coherent Aerospace &amp; Defense, $29.98M (Jun 10 2025), 400 kW from 4×50 kW pulsed-fiber, completion Jan 2027."},
    {tag:"t-clar", h:"HELIOS power dispute persists (60 → 120 vs 150 kW)",
     was:"Original chart flagged the 120 vs 150 kW dispute.",
     now:"Confirmed and kept: delivered as 60 kW-class; growth target cited as 120 kW (R46925 / 2026 DEHEL) or 150 kW (R44175 Jan 2026 / Lockheed). 60 kW delivered figure consistent across sources."},
    {tag:"t-clar", h:"THOR cost: ~$15M vs ~$18M",
     was:"Original chart: THOR ~$15M.",
     now:"AFRL/Wikipedia cite ~$18M built over ~18 months. Shown as a range (~$15–18M)."},
    {tag:"t-add", h:"Big picture: FY2027 ~doubles DE to >$2B",
     was:"Original chart: FY25 unclassified DE $789.7M; 'FY26 topline not disclosed.'",
     now:"FY2027 request exceeds <b>$2B</b> in DE RDT&E, incl. $452M for Golden Dome and a multi-billion counter-drone surge (JIATF-401 five-base pilot, border, World Cup 2026, critical infrastructure)."}
  ]
};
